### ISSUE TITLE
Icon bei Teamverwaltung

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1013]
Falls ich mich auf der Übersichtsseite des OKR-Tools befinde, zeigt die Teamverwaltung das Icon der Teams an. Dieses Icon bleibt jedoch bestehen, auch wenn ich auf die Teamverwaltung wechsle, dabei sollte jedoch ein Icon für die Übersicht erscheinen.

### Absprache
Nach der Absprache mit UX, Paco und Pippo haben sich die Anforderungen geändert. Neu soll der button immer Teamverwaltung heissen auch wenn mann sich auf der Teamwerwaltungsseite befindet. Das heisst der Text als auch das Icon des buttons ändert sich nie. Utilisiert werden soll der button oben links 'Zurück zur OKR übersicht'. Zusätzlich soll noch ein routing auf home bei dem OKR Logo oben links eingeführt werden.
![Image](https://github.com/user-attachments/assets/48aa09c6-d7d5-462d-ad28-543d832d1149)

### Anforderungen
- Abklären mit UX
- ~~Falls ich mich auf der Teamverwaltung befinde, zeigt das UI ein Icon für die Übersicht~~ 
- Der Text des buttons bleibt immer gleich
- Es ist möglich per OKR Logo auf die home Seite zu gelangen

**Comment by RandomTannenbaum** [comment]
There currently is a bug:
When clicking on the okr logo the teams are all unselected but the filter in the top bar is not updated accordingly.
