### ISSUE TITLE
Re enable Pipelines

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1026]
Um die changes vom OKR zu mergen, haben wir die Pipelines deaktiviert, damit wir noch nicht automatisch deployen auf staging sondern erst wenn wir eine stabile version haben. 

### Anforderungen
- Die pipelines laufen wieder und ein Merge auf Main wird direkt auf staging deployed.

### Akzeptanzkriterien
- [ ] Der altbekannte Deploy Flow funktioniert wieder.

**Comment by RandomTannenbaum** [comment]
Fixed on another branch. Maybe close pr if not needed anymore.

**Comment by RandomTannenbaum** [comment]
Fixed on another branch. Maybe close pr if not needed anymore.
