### ISSUE TITLE
Remove ldap properties in the config repo as soon as deployed

### ISSUE THREAD

**Issue by Miguel7373** [puzzle/okr#1031]
Nachdem die neue Version des mains deployed wird, sollte man aus dem config repo die folgenden properties entfernen.

- spring.ldap.urls
- spring.ldap.base
- spring.ldap.username
- spring.ldap.password

Config repo
https://github.com/puzzle/okr-infra

### Anforderungen
- Alle oben stehende properties sind im config repo entfernt.
- sys wurde benachrichtigt, dass sie es ebenfalls entfernen können, wenn es nicht mehr verwendet wird.

**Comment by kcinay055679** [comment]
I notified sys so i hope the ldap user gets deleted
