### ISSUE TITLE
Update Java version

### ISSUE THREAD

**Issue by nevio18324** [puzzle/okr#1032]
Zur Zeit benutzen wir noch die Java LTS Version 17 und wir haben eine erste Dependency welche von der Java LTS Version 17
nicht mehr supported wird

### Anforderungen ###
Die Java Version ist auf die LTS Version 21 geupdated
Die Applikation funktioniert weiterhin einwandfrei

### Akzeptanzkriterien ###
- [x] Alle Anforderungen sind erfüllt
- [x] Falls Fehler aufgetreten sind wurden diese behoben

**Comment by clean-coder** [comment]
f.y.i.o.: **mal kurz lokal ausprobiert**
Habe im `pom.xml` auf `21` gewechselt. Server kommt hoch und JUnit Tests laufen durch. Auch das UI kann man starten.
