### ISSUE TITLE
Objective abschliessen und wiedereröffnen funktioniert nicht richtig

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/okr#1152]
Wenn man beim Abschliessen eines Objectives über das drei-punkte-menu auf "Abbrechen" klickt, dann kommt ein Fehler: "Das Attribut state auf dem Objekt Objective darf nicht null sein." Dies scheint immer zu passieren, egal ob man den Dialog ausfüllt oder nicht.

![Image](https://github.com/user-attachments/assets/b671147b-612b-4aa7-b37c-ef3b21e6dd62)

Wenn man ein Objekt abgeschlossen hat und über das drei-punkte-menu den Wiedereröffnen Dialog öffnet, dann wird das Objective immer wiedereröffnet, sogar wenn man den Dialog wegklickt, den close button oben rechts klickt oder nein klickt.

**Comment by kcinay055679** [comment]
gets fixed in #923
