### ISSUE TITLE
Globale Schriftart

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle/okr#1163]
Als Kunde möchte ich eine einheitliche Schriftart über das ganze Tool und die meist benutzen Browser hinweg.

Im moment ist die Schriftart über das Tool zwar konsistent, jedoch wird die `font-weight` von z.B. Firefox oder Chrome noch immer anders Fett dargestellt. Dies muss unbedingt noch gefixt werden.

**Firefox**
![Image](https://github.com/user-attachments/assets/ee9fd23a-8c79-49fa-a418-c098d6427ff5)

**Chrome**
![Image](https://github.com/user-attachments/assets/ecb269dd-99aa-4a1c-8792-60b3e0ab5714)

> [!NOTE]
> Follow up zu dem Ticket #1109

### Anforderungen
- Die Schriftart Roboto Flex ist über das ganze Tool hinweg implementiert
- Das Tool sieht auf verschiedenen browsern gleich aus
- Der Style für die headings wurde Global definiert
- Unnötige styling Klassen die z.B. `font-weight` oder `font-size` für Elemente definieren wurden entfernt, es sei denn sie haben eine Globale verwendung.

### Akzeptanzkriterien
- [ ] Alle Anforderungen wurden erfüllt
- [ ] Tests wurden wenn nötig ergänzt

**Comment by peggimann** [comment]
> [!CAUTION]
> Use Font which supports multiple weights like OpenSans
