### ISSUE TITLE
Staging Visuell

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1204]
Zur Zeit sieht die Staging und Demo umgebung gleich aus wie die Prod umgebung. Damit wir nicht auf der Falschen Umgebung unsere Tests durchführen, wollen wir diese Umgebungen visuell voneinander unterscheiden können.

### Anforderungen
- Staging und Demo erhalten ein klar ersichtliches styleing.
- Das styleing für Demo wurde mit dem UX Team besprochen
- Prod behält alle styles bei

### Akzeptanzkriterien
- [x] Man erkennt auf den 1. Blick auf welcher Umgebung man ist.
- [x] Das styleing für Demo wurde vom UX Team approved

**Comment by nevio18324** [comment]
### Todo's ###
1. UX Team anschreiben wie man das Styling für Demo gestalten soll
2. Das styling vom Staging abändern
3. Sobald das UX Team geantwortet hat auch das Styling vom Demo anpassen

**Comment by nevio18324** [comment]
### Stand 25.11 ###
Staging ist umgesetzt
Ich und Simon haben uns 2 Optionen ausgedacht
Option 1: Neben dem Puzzle Okr Logo ein Demo text hinzufügen
Option 2: Die hintergründe wie in diesem  [Figma](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=2315-6064&t=e5AAdlxrJ8z2l4Lp-1) anpassen
Ich habe nun mal Pippo geschrieben welche Option er bevorzugt und werde morgen dann das ganze mit Simon anschauen.

**Comment by nevio18324** [comment]
### Stand 28.11 ###
Ich habe heute das Demo environment fertig angepasst ich habe jetzt das fertige Design an Simon
geschickt da mit er das ganze noch absegnen kann und ich suche noch eine Lösung für das new-icon.svg da dieses im Demo die farbe von blau zu weiss verändern muss und die derzeitige Lösung ist mediocre

**Comment by RandomTannenbaum** [comment]
**Stand 06.12.2024**
Ich habe den background auf einen gradient geändert, so wie es hier im Figma definiert ist:
https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=3562-9804&node-type=frame&t=xyasFQuyOJTdaZz7-0

Das Ticket ist soweit ich beurteilen konnte fertig, man sollte jedoch nochmal drüberschauen. Ich glaube das plus-icon beim add-objective hat noch nicht die richtige Farbe für Demo.

**Comment by RandomTannenbaum** [comment]
**Stand 11.12.2024**
Momentan haben wir noch den Fehler, dass der Gradient nicht als gradient angezeigt wird. Das liegt so weit ich gesehen habe daran, wie Figma den gradient ausgibt. Wenn man den gradient richtig einbaut, dann sieht man mehrere Sektionen der Applikation, auf die der gradient einzeln angewandt wird. Vor allem wenn man hearuszoomt.

Es soll noch mal mit Simon Hirsbrunner geschaut werden, ober der gradient wirklich das ist, was er will oder ob die soliden Farben i.o. sind. Dadurch ist auch das mit den einzelnen Bereichen kein Problem mehr.

**Comment by nevio18324** [comment]
### 12.12.2024 ###
Ich habe jetzt nocheinmal Simon geschrieben bezüglich der Background-color und warte jetzt auf seine Antwort.
