### ISSUE TITLE
OKR Frontend - Messung löschen (mit Sicherheitsfrage)

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/okr#136]
Als Kunde möchte ich eine Messung löschen können, damit eine fälschlicherweise erstellte Messung entfernt werden kann.

### Anforderungen
* Eine Messung kann bei der Ansicht _Vergangene Messungen_ gelöscht werden.
* Der Kunde muss vor dem Löschen eine Sicherheitsfrage (Dialog) bestätigen. Der Dialog sollte ähnlich dem Team löschen Dialog umgesetzt werden, mit Datum und aktuellem Messwert:
![Team-löschen.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/b877901d-e908-42d5-8a30-e3fb74be13ed)
* Als Bestätigung oder Fehlermeldung kann man der Toaster verwenden.

### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot
* [ ] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.
* [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle einzutragen_

### Vorgehen
- [x] Icon hinzufügen
- [x] delete method hinzufügen 
- [ ] tests

**Comment by kcinay055679** [comment]
Ich habe der measure-row das delete icon hinzugefügt und mit der implementation der delete Funktion begonnen.
Um das ticket abzuschliessen muss  noch der call in's backend implementiert werden und die entsprechende toaster notification

**Comment by njaeggi** [comment]
Ich habe das Feature implementiert, Styling gemacht, Toastr eingebaut und die kaputten Tests gefixt. Neue Tests können warten, da diese auch beim Keyresult löschen noch fehlen. Das feature funktioniert genau so wie es soll (Button -> Dialog -> Spinner -> Aktualisierung im Frontend). Das einzige was aktuell noch nicht gemacht wird ist das neuladen des Diagrams, da sich dieses auf der gleichen Seite befindet soll beim Löschen einer Messung auch der Punkt dieser Messung verschwinden, ohne die Seite neuzuladen

Ich habe mit Jonas besprochen wie dies ungefähr umgesetzt werden sollte. Ich habe bereits ein Output in der Row definiert der im KeyResultDetail Component die Methode reloadDiagram() auslöst (Mit //TODO gekennzeichnet). In dieser Methode muss das Diagramm neu generiert werden. Nur gibt es ein Problem, das Diagram ist aktuell eine Unterkomponente von KeyresultDescription, was nicht so sein sollte. Zuerst muss die Diagram Komponente um eine Schicht nach oben verschoben werden, in die Komponente KeyResultDetail. Dies führt dazu das man mit dem  Output Event da ist wo man sein will und keine weiteren Events einführen muss. 

Wie genau man das Diagram aktulisieren kann, konnte ich mich leider noch nicht informieren. Wichtig ist das dieses in der KeyresultDetail und im MeasureForm Component implementiert ist.

**Comment by lkleisa** [comment]
Ich habe in der KeyResult-Detail Komponente das Diagram abgelöst und es in die Parent Komponente ausgelagert. Dasselbe dann auch beim MeasureForm. Danach habe ich die Tests angepasst. 
@tuxmatta wird die Implementation für das Aktualisieren des Diagramms vornehmen. 
Tests werden in einer anderen Story gemacht, gleich wie beim Löschen eines KeyResults

**Comment by tuxmatta** [comment]
Für das Aktualisieren des Diagrams existiert die Story: https://github.com/puzzle/okr/issues/152
