### ISSUE TITLE
OKR - Start- + Zielwert sowie der Messwert mit 1 Nachkommastelle

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#138]
Als **Kunde** möchte ich der Start- + Zielwert sowie der Messwert mit 1 Nachkommastelle eintragen können, damit ich zum Beispiel für die Auslastung genauere Werte erfassen kann.

### Hinweis
-  Zuerst Story https://github.com/puzzle/okr/issues/129 umsetzen

### Anforderungen
- Key Result: Start- + Zielwert mit  1 Nachkommastelle
- Messung:  Messwert mit 1 Nachkommastelle
- Backend ist angepasst

### Akzeptanzkriterien
- [x] Backend ist angepasst
- [x] RestSchnittstelle ist angepasst
- [x] Unit- und Integrations-Tests sind nachgezogen
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

#### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

#### Vorgehen
Backend Teil
---
- [x] Branch erstellen
- [x] Backend Änderungen vornehmen (int zu double Wechseln, somit können wir bei den verwendeten "Math" Funktionen direkt die Variable übergeben und müssen diese nicht noch zuerst casten.
- [x] Controller Dokumentation (Swagger) wo nötig ergänzen
- [x] Tests fixen.
---

Frontend Teil
---
- [x] Regex der Validatoren umstellen, so dass diese auch Kommazahlen annehmen (nur eine Nachkommastelle)
- [x] Darstellung der Kommazahlen überprüfen (Diese müssen auch als Double dargestellt werden)
- [x] Tests nachziehen

**Comment by MarcEgliP** [comment]
Frontend konnte noch nicht geändert werden, da hier noch Änderungen vom Pull Request #171 benötigt werden, deshalb ist dieses Ticket solange noch auf blocked.

Was bereits gemacht werden konnte, ist das Regex Update. Damit das Frontend Zahlen mit genau einer Nachkommastelle aufnimmt, musst der Regex "NUMBER_REGEX" in der regexLibrary.ts im shared Modul durch folgenden ersetzt werden: ^[0-9][0-9]*\.?[0-9]?$

Der Regex im selben File des PERCENTS muss durch folgenden ersetzt werden: ^[0-9][0-9]?\.?[0-9]?$|^100$
