### ISSUE TITLE
OKR - Key Result: Erwartete Entwicklung nicht als Muss-Feld

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#143]
Als **Kunde** möchte ich bei den Key Result die Drop Down Liste `Erwartete Entwicklung` nicht als Muss-Feld haben, damit man diese Selektion offen lassen kann.

### Anforderungen
- Das Backend muss Key Results mit optionalen `Erwartete Entwicklung`  verarbeiten können.
- Im Frontend kann beim Erstellen und Editieren eines Key Results die `Erwartete Entwicklung` gesetzt oder offen gelassen werden.

### Hinweis
- Wir verwenden Angular Reactive Form!
- Die Selektion muss über das Drop Down auch wieder gelöscht werden können: `<option value=""></option>`

### Akzeptanzkriterien
- [x] Unit- und Integrations-Tests sind nachgezogen
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Dokumentationen sind nachgezogen (Swagger)
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Validator required aus Key Result Form entfernen
- [x] Feld für das Zurücksetzen der Expectet Evolution implementieren
- [x] Tests nachziehen
- [x] Formatieren und Pushen

**Comment by MarcEgliP** [comment]
Ich konnte hier bereits die Option "None" im Mat select implementieren, allerdings, funktioniert diese noch nicht, wenn man ein Keyresult neu erstellt und ohne das Feld expected Evolution anzuklicken dieses hinzufügen will. Das muss noch untersucht werden + die Tests für das Feature geschrieben werden.

**Comment by kcinay055679** [comment]
Ich habe begonenn die Tests zu implementieren.
Ich habe getestet das die Option abwählbar ist
