### ISSUE TITLE
OKR - Pro Key Result nur eine Messung pro Tag

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#159]
Als **Kunde** möchte ich nur eine Messung pro Tag für ein Key Result eintragen können, da mehrere Messungen am gleichen Tag unnötig sind.

### Anforderungen
- Nur im Backend verifizieren. Fall eine Messung pro Tag für ein bestimmtes Key Result schon existiert folgender HTTP Error zurück senden: HTTP 400  Bad Request, 
-  Als Error-Meldung kann man folgendes verwenden:
`"message": "Only one Messung is allowed per day and Key Result!"`

### Hinweis
- Falls man Zeit hat, kann man im Frontend versuchen, diese Errormeldung im Toaster auf deutsch anzuzeigen.

### Akzeptanzkriterien
- [x] Unit- und Integrations-Tests sind nachgezogen
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Im Backend Liste mit Messungen von Key Result und MeasureDate holen
- [x] Error werfen wenn Liste nicht leer ist
- [x] Im Frontend den Error behandeln
- [x] Backend Tests
- [x] Frontend Tests

**Comment by lkleisa** [comment]
Ich habe auf dem Branch `feature/159-onlyOneMeasurePerDay` angefangen mit dem Umsetzten. Ich habe ein Query gemacht, welches die letzte Messung von einem Key Result anhand des `created_on` Attributes holt. Danach mache ich im MeasureService den Check, ob measure.created_on gleich ist, wie das letzte Measure vom KeyResult .created_on. 
Dies muss noch gründlich getestet werden und auch die Tests sollten noch nachgezogen werden.

**Comment by lkleisa** [comment]
- Es gibt im MeasureRepository eine Methode, welche alle Messungen mit der übergebenen KeyResultId und des MeasureDates zurückgibt
- Wenn  die Liste nicht leer ist, wird ein Error geworfen, mit der Message: `Only one Messung is allowed per day and Key Result!`
- Diese Message wird im Frontend im Toaster angezeigt

- Das Frontend sendet das Datum mit der genauen Zeit in UTC Format an das Backend
- Da wir aber im Backend immer die Zeit 00:00:00 haben wollen, mussten wir dies beheben
- Der Datepicker liefert einen String zurück und kein Date
- Daher machen wir in der save() Methode im MeasureForm ein new Date(measure.measureDate)
- Neu setzen wir unterhalb noch die Zeit auf Mitternacht: `measure.measureDate.setHours(0, 0, 0, 0);`

Probleme:
- Wir wollten im Backend überprüfen, ob die Zeit wirklich 00:00:00 ist
- Da wir aber ein Instand Objekt haben und wir von diesem nicht einfach die Stunden, Minuten und Sekunden lesen können, mussten wir mit ZoneOffset.UTC arbeiten
- Da aber die Pipeline und wir lokal in einer anderen Zeitzone sind, schlugen die Tests entweder lokal oder in der Github Action fehl.

**Comment by lkleisa** [comment]
Aktuelle schlägt die Piepline fehl, da es wieder Probleme mit den Zeitzonen gibt. Dies ist jedoch @tuxmatta am Abklären. Sonst ist das Feature fertig umgesetzt.

**Comment by lkleisa** [comment]
Die Tests laufen soweit lokal, jedoch noch nicht in der Pipeline. Ich werde das am Montag anschauen.
