### ISSUE TITLE
ORK - Aufräum Story

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#162]
Als **Entwickler** möchte ich vor der ersten produktiven Version folgende kleinere Arbeiten noch umsetzen, damit das Tool für die Produktion ready ist:

### Anforderungen
- Statt `Fortschritt` soll überall `Zielerreichung` angezeigt werden.
- Unnötige / nicht umgesetzte Aktionen entfernen
- Es gibt mehrere nicht verwendet Methoden, diese entfernen
- Frontend Tests von it() zu test() ändern
- Alle unused imports entfernen

### Akzeptanzkriterien
- [x] Unit- und Integrations-Tests sind nachgezogen
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Statt `Fortschritt` soll überall `Zielerreichung` angezeigt werden.
- [x] Unnötige / nicht umgesetzte Aktionen entfernen
  - [x] Key Result Duplizieren entfernen
  - [x] Erstellen von Key Result und Messung aus Hamburger Menu entfernen 
- [x] Es gibt mehrere nicht verwendet Methoden, diese entfernen
- [x] Frontend Tests von it() zu test() ändern
- [x] Alle unused imports entfernen
- [x] Nicht verwendete setter und getter entfernen
- [x] Nicht verwendete Dependencies im package.json entfernen

**Comment by lkleisa** [comment]
Ich habe begonnen, die imports und getter und setter aufzuräumen. Ich werde am Mittwoch mit den anderen Sachen weitermachen.
