### ISSUE TITLE
OKR- Frontend Dialog Tests nachziehen

### ISSUE THREAD

**Issue by njaeggi** [puzzle/okr#180]
Als Entwickler möchte ich das die Dilaog Funktion getesetet wird.

#### Anforderung
- Exampletest für ein Modal wurde umgesetzt
- Exampletest kann für weitere Tests als Vorbild genommen werden

#### Akzeptanzkriterien
-  [x] Dropdown darauf wird getestet
- [x] Radio Button darauf wird getestet
- [x] Button darauf (submit) wird getestet
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt
- [ ] E2E Test nachziehen (Aus Story ausgeschlossen)

#### Anpassungen an der Story
Anstatt Tests für Objective, Keyresults und Measure nachziehen, einen Exampletest für Modal aufsetzen, möglichst alle Input-Fälle abdecken damit man sich daran orientieren kann.

=> Testing der focus trap wird ausgelassen, da diese im e2e-Test abgehandelt werden muss

Abgesprochen mit => @peggimann 

#### Vorgehen
- [x] Absprache mit @peggimann bezüglich der Exampletests
- [x] Dialog in HTML mit beschriebenen Elementen umsetzen
- [x] Dropdown eingebunden
- [x] Radio Button eingebunden
- [x] Button eingebunden
- [x] TS für Dialog aufgesetzt (Formular und Validatoren hinzugefügt)
- [x] Überblick über Tests schaffen
- [x] Testsetup implementieren
- [x] Error message über Inputs darstellen
- [x] Tests implementieren
- [x] Review von @kcinay055679 anfordern
- [x] e2e-Tests studieren => Orientierung an Beispiel von @peggimann
- [x] e2e-Tests für ExampleDialog implementieren => Aufgrund von Komplikationen weglassen
- [x] Review @peggimann freigeben

**Comment by MarcEgliP** [comment]
# Aktueller Entwicklungsstand

- Dialog mit FormGroup von Angular ist implementiert
- Tests sind für für BestCase, UseCase und WorstCase geschrieben
- Für alle Tests wurde wenn möglich Harness verwendet
- Externes JSON-File abgelegt damit errormessages von dort aus bezogen werden können
- Die Error Messages wurden mit ihrem zuständigen Error Key von Angular abgelegt

**Comment by MarcEgliP** [comment]
Aktuell blockiert bis die e2e-Tests implementierbar sind.
