### ISSUE TITLE
OKR - Frontend: Beim Aufklappen URL-History nachführen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#186]
Als **Kunde** möchte ich solange ich mich im Overview Tab befinde, dass die aufgeklappten Objectives und Key Results aufgeklappt bleiben, damit ich zum Beispiel nach der Rückkehr von der Detailansicht nicht wieder alles aufklappen muss.

### Hinweis
- In der URL soll der Zustand der aufgeklappten Objectives und Key Result gespeichert sein. So kann man den Link an eine andere Person senden, und dieser erhält dieselbe Ansicht.
- Es soll ein Service erstellt werden, welcher das Navigieren innerhalb der WebApp übernimmt. Alle Navigationsaufrufe der WebApp werden über diesen Service geleitet.
- Es existiert die Story [ORK Frontend - Vorschlag: Status der aufgeklappten Objectives und Key Results erhalten](https://github.com/orgs/puzzle/projects/3/views/1?pane=issue&itemId=18233782), welche mit dieser zusammenhängt. Somit warten wir mit der Umsetzung dieser Story.

#### Anforderungen
- URL passt sich bei aufklappen von Objective- und KeyresultRow an
- Bei neuladen der Seite werden ausgewählte Elemente der URL automatisch geöffnet

#### Hinweis
-  Niklas hat dies bereits zum Teil für die Objectives implementiert
```
    this.route.queryParams.subscribe(params => {
      if (params['objectives'] !== undefined) {
      const selectedObjectives: string[] = params['objectives'].split(',');
       if (selectedObjectives.some(x => getNumberOrNull(x) === this.objective.id)) {
         this.isSelected = true;
       }
      }
     })
```
Dieser Code kann man im ngOnInit von ObjectiveRowComponent einfügen, dieser führt dazu das man in einem QueryParam eine Liste von Ids mitgeben kann von den ObjectiveRows die man aufgeklappt haben will.

#### Akzeptanzkriterien
- [x] Die Story ist nach Anforderungen umgesetzt
- [x] Smoke Tests wurden gründlich durchgeführt
- [ ] Frontend Specs wurden geschrieben

#### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

#### Vorgehen
- [x] Objective History implementieren
- [x] Keyresult History implementieren
- [ ] Testen

**Comment by njaeggi** [comment]
Das Feature ist fertig implementiert und wurde auch bereits gründlich gesmoke testet. Es fehlen noch die Frontend Specs für die ganzen Funktionen und Änderungen. Diese habe ich in Objective und Keyresult Row bereits implementiert. Die anderen werde ich am Donnerstag noch fertig machen.
