### ISSUE TITLE
OKR - Testen: Key Result zeigt kein Prozentwert an wenn keine Messung existiert

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#193]
### IST
Beim Testen hatte es den Anschein, dass folgender SOLL nicht erfüllt ist:

### SOLL
Hat ein Key Result noch keinen Messwert, so soll nur ein `-` für den Fortschritt angezeigt werden.

### Hinweis
- Überprüfen, ob das SOLL in allen Varianten erfüllt ist.

### Akzeptanzkriterien
- [x] Tests sind nachgezogen
- [x] Smoke Tests sind durchgeführt
- [x] SOLL Zustand ist umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [ ] Smoketests durchführen und allenfalls überarbeiten

**Comment by kcinay055679** [comment]
Ich habe das feature ausführlich gesmoketestet, zusätzlich habe ich noch andere Teammitglieder gefragt ob sie das Problem schon einmal hatten.
Da ich weder bei den smoke tests noch bei den Umfragen einen Fehler in der Implementation gefunden habe, schliesse ich das Tickt ohne Änderungen ab

**Comment by kcinay055679** [comment]
Ich habe einen Test implementiert welcher genau diese Funktionalität prüft.
