### ISSUE TITLE
OKR - neue Messung schlägt ohne Datumsauswahl fehl

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#211]
### IST
Erstellt man eine neue Messung und selektiert kein neues Datum (der aktuelle Tag wird angezeigt), so ist der "Erstellen" Button deaktiviert, wenn das Key Result nicht zum aktuellen Quartal gehört.

### SOLL
Wenn der aktuelle Tag ausserhalb des aktuellen Quartals liegt, so soll der letzte gültige Tag des Quartals verwendet werden. 

### Hinweis
- Im nächsten Ausbau wird das Erfassen von Messungen in die Zukunft untersagt. Deshalb kann man den letzte gültige Tag des Quartals verwendet .

### Akzeptanzkriterien
- [x] Tests sind nachgezogen
- [x] Smoke Tests sind durchgeführt
- [x] SOLL Zustand ist umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [ ] ???

**Comment by lkleisa** [comment]
Ist eigentlich gemacht und war schon im Review, es gibt noch ein Problem im measure form componente spec auf Zeile 291, da sollte das aktuelle Datum eigentlich ausserthalb des Datums liegen und der Datepicker sollte das endDate nehmen. Jedoch übernimmt der quarterMock das neue Datum nicht. Beim log auf Zeile 297 ist das Datum richtig, jedoch nimmt der dann trotzdem das aktuelle Datum. Werde es am Freitag nich anschauen.
