### ISSUE TITLE
OKR - Letzte Messung Box mit Infos ergänzen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#219]
Als **Benutzer** möchte ich auf dem Dashboard bei der `Letzte Messung` Box die Info zu dem Start und End-Wert des Key Result sowie der Wert der letzten Messung angezeigt haben, damit man direkt eine Übersicht auf den aktuellen Stand hat.

![Image](https://user-images.githubusercontent.com/4771882/215988138-1b711a83-896e-4c0b-a3a8-13b1a4424419.png)

### Anforderungen
- Falls die Infos vorhanden sind, diese versuchen platzsparend und "schön" anzuzeigen.

### Akzeptanzkriterien
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [ ] ???

**Comment by lkleisa** [comment]
Ich habe die Story umgesetzt wie beschrieben und ein PR für ein Review gestellt.
