### ISSUE TITLE
E2E-Tests

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#229]
Als **Entwickler** möchte ich E2E-Tests ausführen können, damit die Funktionsweise des OKR-Tool sichergestellt werden kann.

### Anforderungen
- Die E2E-Tests sollten mit Cypress umgesetzt werden.

### Hinweis
-  

### Akzeptanzkriterien
- [ ] Dokumentationen sind nachgezogen
- [ ] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Cypress E2E bei Scrum Poker anschauen
- [x] Cypress installieren
- [x] Konfiguration vornehmen
- [x] Keycloak umgehen
- [x] Beispiel Test schreiben

**Comment by lkleisa** [comment]
Blocked due the problem with keycloak sso
