### ISSUE TITLE
Der Progress der Objectives werden nicht korrekt berechnet, wenn die Key Result Messungen Dezimalzahlen enthalten

### ISSUE THREAD

**Issue by bsantschi** [puzzle/okr#235]
Beispiel:

https://okr.ocp.cloudscale.puzzle.ch/?objectives=1003&keyresults=1003&quarterFilter=1&teamFilter=3

Zielwert: 10
Messung: 5.9

Sollte 59% und nicht 50% ergeben.

**Comment by peggimann** [comment]
Fixed
