### ISSUE TITLE
Leeres Frontend

### ISSUE THREAD

**Issue by bsantschi** [puzzle/okr#262]
Wenn ich mich mit meinem User (bsantschi) via SSO einlogge, erhalte ich ein leeres Frontend.

Getestet auf:
- macOS 13.3.1: Chrome 112.0, Safari 16.4, Firefox 112.0
- iOS 16.4.1: Safari 16 und Chrome 112

Vielleicht hilft euch folgender Fehler weiter:

![Screenshot 2023-04-12 at 06 52 13](https://user-images.githubusercontent.com/108862416/231353265-2641df1d-a533-4eb0-b68e-332f4b9c0bc0.png)

**Comment by peggimann** [comment]
Fixed.
