### ISSUE TITLE
Kleine visuelle Anpassungen

### ISSUE THREAD

**Issue by olibrian** [puzzle/okr#267]
Als zukünftiger Anwender hätte ich gerne noch einige visuelle Anpassungen:

- [ ] [Title der App](https://github.com/puzzle/okr/blob/edf79ffc519b895a0235f60e67306a04b3e5d6db/frontend/src/index.html#L5) würde ich "OKR Puzzle" vorschlagen
- [ ] Fav Icon hinterlegen. Aktuell wird ein Angular Icon angezeigt. Wie wärs mit einem Icon aus der [Puzzle Sammlung](https://files.puzzle.ch/apps/files/?dir=/swe/P14_Kommunikation/08_Brand/_Design_Library/01_Icons&fileid=3652327) Wie wäre z.b. die [Rakete](https://files.puzzle.ch/apps/files/?dir=/swe/P14_Kommunikation/08_Brand/_Design_Library/01_Icons/Icons_Sales/SVG&openfile=3795025) oder was ihr wollt..
- [ ] Das Logo rechts in der Nav-Bar ist das Ptime Logo. Dies würde ich auch ersetzten.
- [ ] Bitte Fonts nicht direkt von Google laden, sondern lokal bereitstellen. [Gründe](https://www.dr-datenschutz.de/schadensersatz-urteil-google-fonts-und-die-dsgvo/)

**Comment by peggimann** [comment]
Die ersten 3 Punkte werden mit dem Redesign abgearbeitet und sind bereits für die Umsetzung geplant. Für den letzten Punkt mit den Fonts habe ich ein seperates [Ticket](https://github.com/puzzle/okr/issues/323) erfasst, welches direkt umgesetzt wird. 
Vielen Dank für deine Hilfe!
