### ISSUE TITLE
Auswahl von Besitzer sortieren

### ISSUE THREAD

**Issue by olibrian** [puzzle/okr#270]
**Is your feature request related to a problem? Please describe.**
Bei der Auswahl wird die Liste der möglichen Besitzer unsortiert angezeigt.

![image](https://github.com/puzzle/okr/assets/9592347/12dba23e-3ff1-4f6f-928e-2fe01c2f00c1)

Die ist bei der Erstellung von einem KR (z.b. https://okr.puzzle.ch/objective/64/keyresult/new) der fall

**Describe the solution you'd like**
Die Liste sollte nach dem Vorname sortiert werden. im Idealfall sollte der eingeloggte User vorausgewählt sein.

**Comment by peggimann** [comment]
Beide Punkte sowohl der Preset des eingeloggten Users wie auch die Sortierung, werden mit dem Redesign umgesezt.
