### ISSUE TITLE
Key Result Editieren: Startwert kann nicht verändert werden, da (je nach Typ) nicht sichtbar

### ISSUE THREAD

**Issue by bsantschi** [puzzle/okr#297]
**Describe the bug**
Key Result Editieren: Startwert kann nicht verändert werden, da (je nach Typ) nicht sichtbar

**To Reproduce**
1. Go to https://okr.puzzle.ch/?objectives=44&keyresults=51&quarterFilter=7
2. Click on 'Key Result bearbeiten'
3. Feld 'Startwert' ist nicht sichbar
4. Wechselt man 'Erwartete Entwicklung' auf (z.B.) vermindert, erscheint der Startwert

**Screenshots**
Feld 'Startwert' fehlt:

![Screenshot 2023-07-11 at 05 51 38](https://github.com/puzzle/okr/assets/108862416/4c50ba23-9f66-4aac-9420-53570f7e7772)

Nach dem Wechseln des Typs 'Erwartete Entwicklung':
![Screenshot 2023-07-11 at 05 51 49](https://github.com/puzzle/okr/assets/108862416/8c7b4c66-cd17-43e5-8337-23da9184da22)

### Vorgehen
- [x] Bug reproduzieren
- [x] Debugging
- [x] Testing

**Comment by peggimann** [comment]
Bug is resolved
