### ISSUE TITLE
OKR- Anzeige von Key Results auf der Overview

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#300]
Als **Kunde** möchte ich eine bessere Darstellung eines Key Results haben, welche nicht so stark Verschachtelt ist, damit ich eine bessere Übersicht über die Keyresults erhalte. 

### Anforderungen
- Im Dashboard soll neu ein **Key Result** als Box unter einem Objective und nicht mehr als Zeile ersichtlich sein.
- Die Box erhält die wichtigsten Informationen zu einem Key Result .
- Falls noch kein Checking durchgeführt wurde, so soll Letztes Check-In durch "Noch kein Check-In vorhanden" ersetzt werden.
- Die Komponente wird in die Objective-Dashboard-Komponente eingebunden.  
- Die Anzeige der Key Result Details gehört **_nicht_** zu dieser Story. 
- Das Scorign gehört **_nicht_** zu dieser Story. (Active Zone Balken)
- Confidence gehört **_nicht_** zu dieser Story. 

### Hinweis
![Selected=False, Hover=False(1)](https://github.com/puzzle/okr/assets/113369749/cc213307-990d-45bf-a0b5-9b9cabb1c800)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=351%3A11926&mode=dev) ersichtlich. 
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist  die Definition der Restschnittstelle aufzufinden, Relevant ist der endpoint  **Overview**

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Create Keyresult component
- [x] Add basic box with correct size
- [x] Add hover stylings
- [x] Add dummy data without service connection
- [x] Put component into objectiveColumn
- [x] Display correct data
- [x] Rebase
- [x] Review
- [x] Resolve conversations
- [x] Review again
- [x] Wait for @kcinay055679 's [Branch](https://github.com/puzzle/okr/tree/feature/303-create-overview) to be merged into main, because this branch was created from that branch
- [x] Merge
- [x] Umbruch bei längerem Text

**Comment by RandomTannenbaum** [comment]
**Attention:** There is already some work done in this feature. Here is the Branch: https://github.com/puzzle/okr/tree/feature/300-show-key-results-on-overview
