### ISSUE TITLE
OKR- Objecive Details Card

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#301]
Als **Kunde** möchte ich eine Ansicht eines objectives haben, welche Zusätzliche informationen enthält. 

### Anforderungen
- Im Dashboard soll neu ein **Objective-Detail-Card** als Modal ersichtlich werden, wenn auf ein Objective geklickt wird, änlich wie beim Github Project Board wenn auf eine Story geklickt wird.
- Die Card enthält noch weitere Angaben zu dem Objective.

### Hinweis
![Screenshot from 2023-07-11 11-58-50](https://github.com/puzzle/okr/assets/113369749/910ffe61-ca00-4144-b913-692102da6e4d)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=356-20052&mode=design&t=PwDW85DTxuJ1iAPv-0](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12452&mode=design&t=ZQk9GfxYSrS8YVeN-0)) ersichtlich. 
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist  die Definition der Restschnittstelle aufzufinden, Relevant ist der endpoint  **Objective**

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Sobald das Modal geöffnet ist, ist eine Focustrap vorhanden, durch klicken in den Hintergrund, Space, Escape oder Enter kann das Modal geschlossen werden. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Create objective-detail component
- [x] Create mat-drawer in root html-file and display the component in it
- [x] Add contents
- [x] Add basic styling
- [x] Create focus-trap
- [x] Implement all possible ways to close (Close button, space, escape, enter)
- [x] Final styling
- [x] Show sidenav according to route
- [x] Tests (Have to be implemented)
- [x] Rebase
- [x] Review (Currently in progress by @tuxmatta )
- [x] Merge (Maybe the case, after review of @tuxmatta )

**Comment by MarcEgliP** [comment]
# Aktueller Stand des Tickets (20.09.2023)
- Tests welche noch nicht durchgelaufen sind wurden gefixed (ausgenommen AppComponent Tests)
- Tests in AppComponent wurden mit "xdescribe" ignoriert
- Feedback von @tuxmatta  wurde implementiert
- Story wurde auf "in Review" geschoben
- Branch gerebased

Was gemacht werden muss:
- Tests für ObjectiveDetailComponent sowie für Drawer Content schreiben
- Tests in AppComponent fixen
- Zusätzliches Feedback von @tuxmatta implementieren, falls welches hinzugefügt wurde
