### ISSUE TITLE
OKR- Key Result Detail Card 

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#302]
Als **Kunde** möchte ich eine Ansicht eines Key Results haben, welche Zusätzliche informationen enthält, damit ich den ganzen Umfang des Keyresults sehe. 

### Anforderungen
- Im Dashboard soll neu ein **Key Result-Detail-Card** als **SidePanel** ersichtlich werden, wenn auf ein Key Result geklickt wird, änlich wie beim Github Project Board wenn auf eine Story geklickt wird.
- Die Card enthält wichtige weitere Angaben zu dem Key Result.
- Der Abschnitt Letztes Check-in ist nur ersichtlich, falls bereits ein Check-in durchgeführt wurde, falls nicht wird der Titel ersetzt mit Noch kein Check-in erfasst. 
- Confidence gehört _**nicht**_ zu dieser Story 
- Das Scoring gehört  _**nicht**_  zu dieser Story
- Der Action Plan gehört **_nicht_** zu dieser Story.

### Hinweis
![Screenshot from 2023-07-11 13-30-36](https://github.com/puzzle/okr/assets/113369749/fe6ad338-ddb2-4bff-b820-1486c2528ea3)

- Arbeite mit abstrakten Klassen auch im Frontend und modeliere die Struktur wie im Backend. 

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=356-20052&mode=design&t=PwDW85DTxuJ1iAPv-0](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12452&mode=design&t=ZQk9GfxYSrS8YVeN-0)) ersichtlich. 
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist  die Definition der Restschnittstelle aufzufinden, Relevant ist der endpoint  **Key Result**
- Sprich dich für die Umsetzung kurz mit Simon Hirsbrunner ab (wegen des SidePanels)

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Sobald das Modal geöffnet ist, ist eine Focustrap vorhanden, durch klicken in den Hintergrund, Space, Escape oder Enter kann das Modal geschlossen werden. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Mit Simon Hirsbrunner Unklarheiten klären
- [x] Ein geeignetes Sidepanel finden & Implementieren (mit Jannik absprechen)
- [x] Das man das Sidepanel öffenen kann indem man auf das entsprechende KR drückt
- [x] Die Entsprechenden Daten in dem jeweilige KR anzeigen lassen -> Models für das KeyResult erstellen
- [x] Das das Sidepanel mit Space, Enter & Escape schliessbar ist
- [x] Hinzufügen das es nur möglich ist im KeyResult-Detail-Card zu scrollen solange diese offen ist und nicht auf der Overview
- [x] Eine Focustrap implementieren
- [x] Das Sidepanel und die Daten gemäss der Vorlage im Figma stylen
- [x] Smoke Tests
- [x] Angular Components mit Jest Testen
- [x] Review
- [x] Threads des Reviews abarbeiten (falls vorhanden)
- [x] Mergen
- [x] Review & kurze Demo zu der Detail Card vorbereiten

**Comment by ManuelMoeri** [comment]
Alle Funktionen sollten soweit implementiert und funktional sein. Smoke test wurden von mir durchgeführt. Kann sicher nicht schaden wenn noch jemand anderes Smoke Tests durchführt. Grundsätzlich fehlen noch die Tests und einige Attribute die noch nicht existieren (sind im Code mit einem Kommentar versehen).
