### ISSUE TITLE
OKR- Objective erfassen und bearbeiten

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#304]
Als **Kunde** möchte ich Objectives erfassen können und anschliessend auch bearbeiten können, damit ich die Ziele wie sich mein Bereich weiterentwickeln soll, festhalten kann.

### Anforderungen
- Das Form fürs erfassen eines Objectives soll als Dialog in mitten des Bildschirms erscheinen. 
- Sobald der Dialog geöffnet ist, soll dieser in einer Fokustrap sein. 
- Es wird nicht der Router zum Navigieren verwendet.
- Falls der Button zum erfassen eines Objectives von einem Team gewählt wird, soll dieses Team vorausgefüllt werden.
- Falls das Objective bearbeitet wird, sollen die Werte des objectives als Preset im Formular sein.   
- Die Buttons auf dem Dashboard sind erstellt. 
- Die Buttons auf dem Form sind erstellt und haben ihre Funktionalität.
- Info Icons gehören _**nicht**_ zu dieser Story.
- Das Feld Bezug gehört _**nicht**_ zu dieser Story. 
### Hinweis
![Objective_neutral](https://github.com/puzzle/okr/assets/113369749/2aacd299-e1d6-4d48-819c-99e8b32dd4b2)

![Objective_division](https://github.com/puzzle/okr/assets/113369749/7a1aacf8-46b0-4307-a2a4-80bd7d836c3d)
![Objective_bearbeiten](https://github.com/puzzle/okr/assets/113369749/847521e1-1e33-4082-b13f-745aa9dc0c95)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12114&mode=design&t=ZQk9GfxYSrS8YVeN-0) ersichtlich. 
- Beachtet insbesondere die Presets der Forms, je nach dem von wo aus das Form aufgerufen wird.  
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist  die Definition der Restschnittstelle aufzufinden, Relevant ist der endpoint  **Objective**

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Die Funktionalität auf den Buttons in den Anderen Komponenten ist hinterlegt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Dialog erstellen
- [x] Erstellen funktionalität 
- [x] update Funktionalität
- [x] Werte automatisch einfüllen
- [x] Backend requests
- [x] Reload auf overview
- [x] Toaster für errors
- [x] Fix frontend tests
- [x] Backend tests
- [x] Rebase
- [x] Implement feature to open create-keyresult-dialog after creation of objective
- [x] Write missing frontend tests
- [x] Fix error in console when creating keyresult after objective
- [x] Maybe rebase again
- [ ] Review
- [ ] Merge

**Comment by kcinay055679** [comment]
Das feature ist soweit mit allen Anforderungen fertig abgesehen von folgenden Tests:
Frontend:

- [ ] ObjectiveForm component (onInit)
- [ ] Objective Component (Dialog open on click on option, and load values into form)
- [ ] Team component (refresh functionality)
- [ ] Team component (Open dialog after click on new button)

**Comment by RandomTannenbaum** [comment]
- onInit tested
- tested setting of values and loading values into form
- tested refresh functionality with smoke testing
- Open dialog after click on button is an end-to-end test and was not tested
