### ISSUE TITLE
OKR- Key Result erfassen und bearbeiten

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#305]
Als **Kunde** möchte ich Key Results erfassen können und anschliessend auch bearbeiten können, damit ich die Key Results zu den Zielen in meinem Bereich, festhalten kann.

### Anforderungen
- Das Form fürs erfassen eines Key Results soll als Dialog in mitten des Bildschirms erscheinen. 
- Dabei gehört die Komponente welche zwischen Metrisch und Ordinal wechselt _**nicht**_ zu dieser Story.
- Der Action Plan gehört _**nicht**_ zu dieser Story.
- Der Preset des Users gehört _**nicht**_ zu dieser Story.  
- Die Funktionen der Buttons auf dem Objective sind **nicht** hinterlegt.
- Die Info Icons gehören **_nicht_** zu dieser Story. 

### Hinweis
![Key Result bearbeiten Metrisch](https://github.com/puzzle/okr/assets/113369749/76c72ac2-b26f-4a51-8c4d-e61220a4d510)

![Key Result bearbeiten Ordinal](https://github.com/puzzle/okr/assets/113369749/f1c2fb38-5d5b-4360-a823-f395a5e5dd92)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12162&mode=design&t=ZQk9GfxYSrS8YVeN-0) ersichtlich. 
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist  die Definition der Restschnittstelle aufzufinden, Relevant ist der endpoint  **Key Result**

### Akzeptanzkriterien
- [ ] Die Ausgabe entspricht dem verlinkten Template. 
- [ ] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [ ] Die Funktionalität auf den Buttons in den Anderen Komponenten ist hinterlegt. 
- [ ] Angular Komponente und das Template sind mit Jest getestet
- [ ] Smoke Tests wurden gründlich durchgeführt
- [ ] Die benötigten Daten werden mittels Service + RxJS geladen.
- [ ] Dokumentationen sind nachgezogen
- [ ] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Create key-result-dialog component
- [x] Open this dialog when clicking on "Key Result hinzufügen" Button in objective-column  component
- [x] Set Dialog to correct size
- [x] Add placeholder title to dialog
- [x] Input Felder erstellen
- [x] Buttons erstellen
- [x] Dialog schliessen und öffnen (Speichern & Neu)
- [x] Dialog Grösse anpassen 
- [x] FormGroup umsetzen
- [x] Edit und Speichern erstellen 
- [x] Overview nachladen wenn saveKeyResult()
- [x] Bearbeitetes KR nur in aktuellem Objective speichern
- [x] Bei Delete Function KR entfernen
- [x] Mehrer mit Speichern & Neu erstellen können
- [x] INFO für Benutzer wenn KR nicht gelöscht werden kann
- [x] KeyResult Service anbinden 
- [x] Smoke Testing
- [x] Tests schreiben
- [x] Tests fixen
- [x] Button styling anpassen an 304 -> siehe Kommentar

**Comment by RandomTannenbaum** [comment]
**Attention:** There is already some work done for this ticket. See linked draft pullrequest.

**Comment by lkleisa** [comment]
Guten Tag. Das Ticket ist wie gewünscht umgesetzt. Review ist aprooved bis auf einen Punkt: Styles. Das Styling ist grösstenteils vom Ticket #421 (Objective Dialog) übernommen. Diese haben jetzt aber noch geändert und sind auf 304 Branch besser umgesetzt. Es sollen die Klassen add-flat-primary-button und add-flat-secondary-button entfernt werden oder auf jeden Fall kein `!important` verwendet werden. 
*Schaue gut zu diesem Ticket, es wurde mit Liebe umgesetzt*

**Comment by tobiasstern** [comment]
Zurzeit nicht testbar. Wenn ich ein Key Result abspeichern will, tritt ein Fehler auf, vgl. Screenshot:


![Image](https://github.com/puzzle/okr/assets/11408951/113213af-ee5c-4555-a350-a97424e53732)

**Comment by tobiasstern** [comment]
Ich konnte es nun testen. Grundsätzlich funktioniert es gut! Hier habe ich noch ein paar visuelle Optimierungen gesammelt:
