### ISSUE TITLE
OKR- Check-in erfassen und bearbeiten

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#306]
Als **Kunde** möchte ich den Fortschritt eines Key Results erfassen, mittels Check-in.

### Anforderungen
- Das Form fürs erfassen eines Check-in soll als Dialog in mitten des Bildschirms erscheinen. 
- Der Preset bei Metrischen Keyresults soll als Default den Startwert haben oder den Wert des letzten Check-in.   
- Die Confidence soll als Slider eingegeben werden können. 
- Es Existieren zwei Forms Metrisch und Ordinal

### Hinweis
![Screenshot from 2023-07-11 15-19-27](https://github.com/puzzle/okr/assets/113369749/fd8a56b9-a329-4857-b247-821d36dd7bcd)

![Check-In metrisch](https://github.com/puzzle/okr/assets/113369749/801093f0-d825-4169-b267-fa74b1688b8f)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12350&mode=design&t=ZQk9GfxYSrS8YVeN-0) ersichtlich. 

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Die Funktionalität auf den Buttons in den Anderen Komponenten ist hinterlegt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- UX Review step by step Umsetzen
- Pro UX-Bug 1 Commit
- Reviewen lassen von @kcinay055679 
- Review umsetzen
- Review an @peggimann stellen

**Comment by tobiasstern** [comment]
Habe es auch getestet, funktioniert soweit gut! Hier ein paar Dinge, die man verbessern kann:

**Der User Flow in Check-in History:**

1. Wenn ich ein Check-in in der History entweder bearbeite oder lösche, muss ich danach den “Schliessen” button zweimal drücken, um die History zu schliessen.
2. Wenn ich ein Check-in in der History bearbeite und im Schritt 1 den “abbrechen” button wähle, wird die ganze History geschlossen statt nur das Bearbeiten. Im Schritt 2 funktioniert dies aber.

**Siehe auch nachfolgende Bilder für weitere Verbesserungen.**

![Image](https://github.com/puzzle/okr/assets/11408951/a575e144-ecef-494b-9e38-4e6a64ff35e7)



![Image](https://github.com/puzzle/okr/assets/11408951/c24a59ea-1431-4f08-9e4e-69a23296d064)



![Image](https://github.com/puzzle/okr/assets/11408951/783e646c-43e7-4354-82be-a5c5a1ec3f23)




![Image](https://github.com/puzzle/okr/assets/11408951/b8fc8f2a-bc6b-4a58-b2f6-ada82eb3fe30)



![Image](https://github.com/puzzle/okr/assets/11408951/7de7df3e-7263-4e09-bdba-8a06b717ae5e)

**Comment by MarcEgliP** [comment]
# Aktueller Stand:
- Anhand der oben angehängten Reviews von UX sieht man den Fortschritt
- Alles wurde Resolved bis auf die Check-In History und das Penetrationtesting der Formating Pipe

# Was gemacht werden muss
- Check-In History neu  aufbauen (nach UX-Vorschlag, siehe Figma)
- Ausserdem muss die Pipe im Formular des KeyResults eingebaut werden.
