### ISSUE TITLE
OKR-Backend reformatieren des Objective

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#308]
Als **Kunde** möchte ich ein Objective erfassen und dieses repräsentativ in der Datenbank abspeichern.

### Anforderungen
- Das Model des Objective ist wie im Klassendiagram beschrieben umgesetzt, Alignment gehört _**nicht**_ zu dieser Story.
- Die Records, Mapper, Repositories, Services und Controller sind angepasst und erüllen die Definition der REST-Schnittstelle.
- Die Validierung ist wie anhand des Beispiels beim Team umgesetzt.
- Die Änderungen an der Datenhaltung ist mittels Migrationsskript umgesetzt. 
- Für bestehenden Daten nach altem Datenbankschema ist die Funktionalität der Applikation weiterhin gewährleistet. 

### Hinweis
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist sowohl das Klassendiagram, wie auch die Definition der Restschnittstelle aufzufinden.  
-  Weiter sind im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12091&mode=design&t=ZQk9GfxYSrS8YVeN-0) die Zusammenhänge zwischen den Komponenten ersichtlich. 

### Akzeptanzkriterien
- [x] Änderungen am Datenbankschema sind in **_einem_** Migrationsskript umgesetzt.
- [x] Die Unit und IT-Tests sind nachgezogen mit minimum 80% Testabdekung
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Überblick über Vergleichsstory verschaffen #354 
- [x] Vorgehen hier dokumentieren
   - [x] ObjectiveController (v2) anpassen
   - [x] ObjectiveService anpassen (PersistenceService aufrufen)
   - [x] Validierung nach Beispiel in Team einbauen
   - [x] Migrationsskript aufsetzen
   - [x] Modeländerungen einführen
   - [x] Testen

**Comment by MarcEgliP** [comment]
# Stand des Tickets
- Der Controller wurde angepasst
- Der ObjectivePersistenceService wurde implementiert
- Der ObjectiveValidationService wurde begonnen

**Comment by lkleisa** [comment]
### Update - Mittwoch 23. August
- Das Skript ist soweit erstellt und umgesetzt (hat v2_0_1 weil Quarter v2_0_0 hat)
- Die Modeländerungen sind implementiert
- Das Enum State ist in der Datenbank als String hinterlegt

**Comment by lkleisa** [comment]
## Zum Abklären
- Was ist wenn ein Objective update wird, wird dann der letzte User als createdOn genommen? Ist das überhaupt möglich das ein anderer ein nicht von ihm erstelltes Objective ändern kann?

**Comment by lkleisa** [comment]
## Update - Freitag 25. August
- Tests für ObjectiveController angepasst
- Tests für ObjectiveBusinessService geschrieben
- Tests für ObjectiveValidationService geschrieben
