### ISSUE TITLE
OKR-Backend reformatieren der Key Results

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#309]
Als **Kunde** möchte ich ein Key Result erfassen und dieses repräsentativ in der Datenbank abspeichern.

### Anforderungen
- Das Model des Key Results ist wie im Klassendiagram beschrieben umgesetzt, Action gehört _**nicht**_ zu dieser Story.
- Die Records, Mapper, Repositories, Services und Controller sind angepasst und erüllen die Definition der REST-Schnittstelle.
- Die Validierung ist wie anhand des Beispiels beim Team umgesetzt.
- Die Änderungen an der Datenhaltung ist mittels Migrationsskript umgesetzt. 
- Für bestehenden Daten nach altem Datenbankschema ist die Funktionalität der Applikation weiterhin gewährleistet. 

### Hinweis
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist sowohl das Klassendiagram, wie auch die Definition der Restschnittstelle aufzufinden.  
-  Weiter sind im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12091&mode=design&t=ZQk9GfxYSrS8YVeN-0) die Zusammenhänge zwischen den Komponenten ersichtlich. 
-  Da beim Key Result neu eine Abstrakte Klasse verwendet wird um beide Arten von Key Results darzustellen verwenden wir neu die [Single-Table-Strategy](https://thorben-janssen.com/complete-guide-inheritance-strategies-jpa-hibernate/) von Hibernate. Ein weiteres [Beispiel](https://dzone.com/articles/introduction-spring-data-jpa-inheritance-rest-app) für die Single-Table-Strategy. 
- Auch das [Builder-Pattern](https://dev.to/karthikrg/implementing-builder-pattern-abstract-class-3c1l) soll abstrahiert werden. 

### Akzeptanzkriterien
- [x] Änderungen am Datenbankschema sind in **_einem_** Migrationsskript umgesetzt.
- [x] Die Unit und IT-Tests sind nachgezogen mit minimum 80% Testabdekung
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Entity anpassen
- [x] Builder anpassen
- [x] DTO anpassen
- [x] Schauen, dass Builder läuft
- [x] Schauen, wie InheritanceType-SingleTable die Aufteilung handelt
- [x] Migrationsskript erstellen und schreiben
- [x] Controller aufräumen
- [x] BusinessService anpassen
- [x] ValidationService erstellen
- [x] Annotations in Builders entfernen
- [x] Abhänige Klassen anpassen
- [x] DTO in tests anpassen
- [x] Schauen, dass get Abfrage alles nötige zurück bringt
- [x] KeyResultController Swagger Schema
- [x] Abfragen zum Obigen ausprobieren für Ordinal und Metric
- [x] Abklären, ob bei Rückgabewert "nur" DTOS sein sollen oder die einzelnen Werte
- [x] ValidationError `must not be null` von irgendwo entfernen (bei Tests welche auf die Attribute prüfen)
- [x] Alte Tests fixen
- [x] ValidationTest schreiben
- [x] BusinessServiceTest anpassen
- [x] Validierung für toKeyResult verwenden
- [x] Schauen, dass update funktioniert
- [x] Migration beheben
- [x] Persistence Tests fixen
- [x] Smoke testing
- [x] OverView Tests fixen
- [x] Die anderen Tests noch fixen

**Comment by lkleisa** [comment]
## Update - Montag 28.08
- Controller aufgeräumt
- ValidationService erstellt
- BusinessService aufgeräumt
- Abstrakte Klassen erstellt und mit Builder begonnen 

### Nächste Schritte 
- Builder fertigmachen
- DTO anpassen
- Andere abhängige Klassen anpassen
- Mapper anpassen

**Comment by lkleisa** [comment]
## Update - Mittwoch 30.08
- Migrationsskript erstellt und fertiggemacht
- Builder so angepasst, dass er funktioniert
- Angefangen mit abstraktem KeyResultMapper und Unterteilung von Ordinal und Metric in den Mapper und DTO's

### Nächste Schritte
- DTO's und Mapper zum Laufen bringen
- Abhängige Klassen anpassen
- KeyResultMeasure Model anpassen (braucht es dies noch)

**Comment by lkleisa** [comment]
## Update - Freitag 01.09
- ValidationTest wurde erstellt und bis auf einen Test funktioniert alles
- Probiert, neue KeyResults zu erstellen
- Andere Tests angepasst

### Nächste Schritte
- Herausfinden, warum KR nicht gespeichert werden kann
- Herausfinden, von wo `must not be null` kommt
- Tests fertigstellen
- Swagger Schema anspassen

**Comment by lkleisa** [comment]
## Update - Montag 04.09
- Create und Update von KeyResult funktioniert jetzt
- Check für Ordinal und Metrisch funktioniert nun
- Rückgabewerte ist so wie in Dokumentation angepasst (mit DTO von CheckIn, Owner und CreatedBy)
- Swagger Schema ist angepasst
- Tests sind alle angepasst und die alten laufen
- Testabdeckung ist erreicht

### Nächste Schritte
- Persistence Tests zum Laufen bringen 
- Smoke Testing
- Code aufräumen
- Rebase
