### ISSUE TITLE
OKR- Draftstatus / Abschluss eines Objectives

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#311]
Als **Kunde** möchte ich einen Draftstatus für meine Objectives und für meine Key Results, damit ich diese zuerst überprüfen kann, bevor ich diese publiziere. 

### Anforderungen
- Es existiert ein Draftstatus für Objectives und für Key Results
- Der Draftstatus ist in der Datenbank als eigener Status hinterlegt
- Ein Draft, kann nur von entsprechenden Rollen eingesehen werden
- Der Draft ist im Frontend als Draft gekennzeichnet.

### Hinweis
- TBD

### Akzeptanzkriterien
- [x] Die Funktionalität ist mit Unit und IT-Tests getestet. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Draft im Backend implementieren 
- [x] Draft im Frontend implementieren 
- [x] Backend: 
  - [x] Neues Model 
  - [x] Neue Tabelle
  - [x] Neuer Endpoint
  - [x] Testing
- [x] Frontend:
  - [x]  Neuer Service
  - [x] Erstellen
  - [x] Löschen
  - [x] Testing
- [x] Das Menu anpassen, dass es anders ist, wenn Objective schon abgeschlossen ist
- [x] Frontend MenuFunktionen: 
  - [x] Abschliessen: 
    - [x] Dialog styling
    - [x] Dialog Funktion implementieren
  - [x] Wiedereröffnen
    - [x] Von Successful oder Not Successful zu OnGoing 
  - [x] Freigeben 
  - [x] Zuerst ein Confirm Dialog
    - [x] Von Draft zu OnGoing 
- [x] MenuEntries anpassen (bei OnGoing kann nicht freigegeben werden, bei Draft kann nicht abgeschlossen werden) -> Hat TODO in code (objective.component.ts Line 90 & 96)
- [x] Overview aktualtisieren
- [x] Evt. Dreipunktemenu schliessen nach Freigabe
- [x] Review

**Comment by lkleisa** [comment]
Die Funktionalität sollte vorhanden sein, jetzt geht es noch um Styling vom neuen Dialog, die Overview aktualisieren und kleinen Fixes
