### ISSUE TITLE
OKR - Applikations Header

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#324]
Als **Kunde** möchte ich Auf einen Blick erkennen, um welche Applikation es sich handelt, sowie die Möglichkeit einige globale Einstellungen vorzunehmen. Damit dies Gelingt soll ein Puzzle Header der Extra fürs OKR Tool ist eingesetzt werden. 

### Anforderungen
- Im Dashboard ist neu der Applikationsheader Eingebaut werden , der In zwei Teile eingeteilt ist. 
- Der obere Teil des Headers soll permanent sichtbar sein
- Der untere Teil des Headers, mit den Filtern soll bei einem scroll down event nach oben verschwinden und bei eine scroll up event wieder erscheinen.  
- Die Filterkomponenten auf dem Header gehören **_nicht_** zu dieser Story
- Das anzeigen des eingeloggten Benutzers gehört **_nicht_** zu dieser Story. 

### Hinweis
![Image](https://user-images.githubusercontent.com/113369749/256807506-7d270618-ef2c-406e-b333-23727497c598.png)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=351%3A18795&mode=dev) ersichtlich. 
- Es werden für diese Story keine Zusätzlichen dienste Zum laden der Daten benötigt. 

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Angular Komponente und das Template sind mit Jest getestet (Nicht erfüllt, wegen unten beschriebener Situtation)
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] PuzzleShell importieren
- [x] Okr Komponent aus Shell heraussuchen, diese unter diesem Punkt in der Reihenfolge der Insertion aufführen
   - Puzzle-Topbar
   - Puzzle-Bannner
   - SVG von Mockup (Figma)
- [x] Komponenten nach erstelltem Plan einbinden
- [x] Oberer Teil des Headers sticky machen
- [x] SmokeTesten

**Comment by MarcEgliP** [comment]
# Aktueller Stand des Tickets

- Header und Banner wurden implementiert
- Margin Top vom Banner zum Header wird dynamisch generiert
- Header ist fixed to top
- Banner verschwindet on scroll, ist aber noch etwas buggy

# Was gemacht werden muss
- Banner soll nur verschwinden, wenn man nach unten scrolled
