### ISSUE TITLE
OKR- Quarter Filter

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#325]
Als **Kunde** möchte ich eine Möglichkeit haben um zu bestimmen,  in welchem Quartal die dargestellten Informationen sind. 

### Anforderungen
- Im Header ist ein Dropdown erstellt, welches in folgender Reihenfolge die Quartale darstellt:
    1.     aktuelles Quartal
    2.     nachfolgendes Quartal
    3.     letztes Quartal
    4.     vorletztes Quartal
    5.     vorvorletztes Quartal
    6.     vor einem Jahr 
- Beim laden der Seite, sofern im url nicht anders spezifiziert, ist standartmässig das aktuelle Quartal ausgewählt
- Es kann jeweils nur ein Quartal ausgewählt sein single select
- Es werden nur Objectives angezeigt, welche im ausgewählten Quartal angehörig sind.  
- Das Dropdown soll unter dem Feld aufgehen und das ausgewählte Quartal hebt sich von den anderen ab. 
- Der Quarterfilter ist auf dem Header eingefügt. 
- Der Quarterfilter ist im Url ersichtlich

### Hinweis

![Image](https://user-images.githubusercontent.com/113369749/256814495-2886bbf0-c464-49d0-9878-c23502e57d5f.png)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=355%3A18218&mode=dev) ersichtlich. 
-  Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist  die Definition der Restschnittstelle aufzufinden, relevant sind die Endpoints  **Overview** und **Quarter**
- Die REST Schnittstelle zu der Overview wird in der Story #450  angepasst.

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Quarter-id aus url im Komponent onInit extrahieren
- [x] Service call mit korrekter quarter id
- [x] Overview anzeigen
- [x] Filter component bauen
- [x] Filter component auf Header Banner einbauen
- [x] Filter funktion einbauen -> auf korrekte route navigieren
- [x] Smoke testing
- [x] Unit testing
- [x] Rebase
- [x] Review (Manuel, Yanick, Marc, Lias)
- [x] Review von @peggimann oder @tuxmatta

**Comment by RandomTannenbaum** [comment]
Notes:
- Style width and height of dropdown
- Do options have to have `cursors: pointer`
- Is option styling okay
- Align dropdown to correct position

**Comment by RandomTannenbaum** [comment]
Notes 12.10.2023:
- [ ] Test OverviewBusinessService
- [ ] Test OverviewValidationService
