### ISSUE TITLE
OKR - Confidence Component (Edit)

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#332]
Als **Kunde** möchte ich meine Confidence angeben können, und diese auch updaten und auslesen. Die Confidence beschreibt meine Zuversicht den Targetbereich des Key Results zu erreichen und ist inital beim Erstellen des Key Results bei 5/10. 

### Anforderungen
- **Dieses Ticket ist nur für die Variante des Editierens (Anzeige ist ein eigenes Ticket #394)**
- Die Confidence Komponente soll mit und ohne Slider dargestellt werden können
- Falls sie mit dem Slider dargestellt ist, soll sich die Zahl und der Slider automatisch synchronisieren.
- Falls noch kein Check-in durchgeführt wurde, so ist die Confidence bei 5/10. 
- Die Confidence Komponente ist implementiert.  
- Das Zahlenfeld ist kein Inputfeld, nur Anzeige
- Der Slider soll die einzelnen Steps mit Ticks anzeigen. 
- Sprich dich nochmals mit UX über die Anforderungen an den Slider ab (wie kann man den Wert ändern, wie ist es mit dem Tab-Index, ...)

### Hinweis

![Image](https://user-images.githubusercontent.com/113369749/256861404-79375ab1-c0ea-4e6e-917c-fd9b3daa730c.png)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12359&mode=design&t=L7lpNDmtKGEfBuzi-4) ersichtlich. 
-  Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist  die Definition der Restschnittstelle aufzufinden, relevant sind die  Endpoints **Overview** und **Key Result**

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Show text with bar
- [x] Bar can be hidden by input property
- [x] Change bar color by overriding angular material theme
- [x] implement tests

**Comment by tuxmatta** [comment]
Mit UX abklären, ob nicht anstelle des Input-Feldes auf eine andere Art mit der Tastatur die Confidence eingestellt werden kann.
