### ISSUE TITLE
OKR - Check-in History

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#333]
Als **Kunde** möchte ich die vergangenen Check-ins mit den jeweiligen Werten einsehen können.

### Anforderungen
- Die Check-in History ist erstellt
- Da die beiden Properties: **Massnahmen** und **Veränderung seit letzter Messung** erhalten beliben, wird nicht nur ein String dargestellt, sondern eine saubere auflistung der letzten Messung. Speziell sollen Zeilenumbrüche richtig dargestellt werden. 
- Die Check-in History kann von dem jeweiligen Key Result Detail aufgerufen werden
- Front und Backend gehört zu dieser Story.

### Hinweis

![Image](https://github.com/puzzle/okr/assets/113369749/d0fae733-cb7f-41b0-a35e-f2d36288c241)

-  Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12415&mode=dev) ersichtlich. 
- [Check-in History](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12415&mode=design&t=ZQk9GfxYSrS8YVeN-0) soll von Keyresult aufgerufen werden können.  

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Das Backend ist getestet, sowohl Unit-, wie auch Integrationstests sind erstellt
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Die Funktionalität auf den Buttons in den Anderen Komponenten ist hinterlegt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Service erstellt und API entpoint angebunden
- [x] Dialog erstellt
- [x] Elemente im Dialog werden schön dargestellt
- [x] tests
- [x] Dialog responsive machen
- [x] Box shadow hinzufügen
- [x] Rebase
- [x] Review
- [x] Merge

**Comment by RandomTannenbaum** [comment]
Dialog hat nun keine max-width mehr und content füllt den gesamten Dialog aus
