### ISSUE TITLE
OKR- Formatieren beim Commit

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#335]
Als Entwickler will ich eine saubere Codebasis und überall die gleiche Formattierung.

**Akzeptanzkriterien**
- Sowohl die Frontend- , wie auch die Backendformattierung wird automatisch bei jedem commit ausgeführt, so dass nur noch Formattierter code gepusht werden kann.
- Es existiert ein format.yml in den Workflows, wo die Formatierung hinterlegt ist.

**Comment by MarcEgliP** [comment]
Vorgehen:
- [ ] Githooks im workflow.yml anschauen + verstehen (precommit)
- [ ] Formatierung on-commit implementieren (prettier, andere Formatierer)
- [ ] Falls pre-commit Formatierung funktioniert, validate der Formatierung des Frontends ausschalten
- [ ] Alternativ: Formatierung on-push, prettier Validierung eingeschaltet lassen

**Comment by MarcEgliP** [comment]
**Momentaner Fehler:** 
- Es wird ein forcepush erfordert, um die changes auf einen Branch zu laden, nachdem die Files formatiert wurden.

**Fehlerbehebung:**
- [ ] Git Dokumentation durchlesen, wie der pre-commit hook funktioniert
- [ ] Überprüfen ob ein git commit amend nötig ist / Fehler verursacht
- [ ] Prüfen ob es ein lokales Gitproblem ist
- [ ] Fehler aufgrund der von oben gewonnenen Erkenntnisse beheben
