### ISSUE TITLE
OKR - Info Icons

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#376]
Als Benutzer möchte ich, falls ich eine unbekannte Situation antreffe, die Möglichkeit haben, die Hilfeseite vom Wiki aufzuruffen. 

### Anforderungen
Im Fixen Header ist wie bei PTime ein Rettungsring implementiert, welcher die Wikiseite vom OKR-Tool in einem neuen Tab öffnet. 

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Die Funktionalität auf den Buttons in den Anderen Komponenten ist hinterlegt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

**Comment by ManuelMoeri** [comment]
Ein erster Prototyp des Help-Icons wurde Implementiert. Er hat die ungefähre Form von dem auf dem PTime.

Auf Absprache mit Marc habe ich das Icon von [hier](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:support:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=help&icon.platform=web) als SVG implementiert. Der Name des SVG's ist 'life-ring' und es wurde unter shared/assets/icons hinzugefügt. Der Link auf den [Wiki-eintrag](https://wiki.puzzle.ch/Puzzle/OKRs) wurde ebbenfalls implementiert.

Falls wir dieses Icon nicht verwenden möchten ist [hier](https://puzzle.github.io/puzzle-shell/?path=/docs/puzzle-shell-components-icons--docs) die Seite aller Puzzle Shell Icons zu finden. Der Retungsring der jedoch dort unter 'full list of icons' zu finden war, enstsprach nicht dem Rettungsring vom PuzzleTime.

Ausserdem wurde im CSS noch eine Klasse namens 'help-icon' erstellt sodas der Ring einen graulichen Farbton hat.
