### ISSUE TITLE
Angular Update Version to 16

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#396]
Als **Kunde** möchte ich das OKR-Tool mit aktueller Technik umgesetzt haben, damit die Wartung und Weiterentwicklung einfach bleibt.

### Anforderungen
- Folge dem [Update Guide von Angular](https://update.angular.io/)
- Pakete auch updaten

### Akzeptanzkriterien
- [x] Die Angular Abhängigkeiten sind auf der aktuellen Version 16 aktualisiert
- [x] Die restlichen Abhängigkeit sind wo einfach möglich aktuell
- [x] Alle Tests sind erfolgreich
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Version auf 15 erhöhen
- [x] Version auf 16 erhöhen
- [x] Dependencies auch updaten
- [x] Smoke testing

**Comment by lkleisa** [comment]
# Abklären
- [ ] Soll `@Injectable({ providedIn: 'root', })` entfernt werden? -> https://angular.io/guide/update-to-version-15#v15-dp-04
