### ISSUE TITLE
Kein horizontales Scrolling in der Overview

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#400]
Als **Kunde** möchte ich kein horizontales Scrolling bei der Overview, damit diese einfach bedienbar bleibt.

### Anforderungen
- Die Boxen der Objectives sollen bei Bedarf umbrechen
- Die vertikale Scroll-Leiste soll eine bestimmte Breite haben

### Hinweis
- Beide Anforderungen mit Simon besprechen.

### Akzeptanzkriterien
- [x] Das horizontale Scrollen ist ausgeschaltet und die Boxen brechen um
- [x] Die vertikale Scroll-Leiste ist nicht zu schmal (mit verschiedene Browser testen)
- [x] Alle Tests funktionieren weiterhin
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Jeziges Scrolling anschauen -> Notizen machen & unklarheiten klären
- [x] Horizontales Scrolling im Code disablen
- [x] Umbrechen der KR bei einem bestimmten Punkt definieren
- [x] Mit UX absprechen
- [x] Breite der Scrollbar anpassen (Konnte nicht erfüllt werden, von @peggimann bestätigen lassen)
- [x] Smoke Testing von mir
- [x] Testing (Nicht nötig)
- [x] Review & Smoke Testing (Lias, Yanick, Marc) 
- [x] Review von Paco oder Jonas
- [x] Falls nötig sachen nach den Reviews anpassen
- [x] Mergen

**Comment by ManuelMoeri** [comment]
Note vom 18.10 2023:

Sämtliche Funktionen wurden hier abgeschlossen. Das einzige das noch fehlt ist die Anpassung des Buttons wenn die drei Objectives nebeneinander sind, und der "Objective hinzufügen" button eine Zeile nach unten rutscht. Dies geschieht wenn der Bildschirm leicht dünner wird. Alle anderen sachen die verändert wurden, sind mit UX abgesprochen und es wurde so von  Ihnen approved.
