### ISSUE TITLE
Header und SidePanel

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#407]
Als **Kunde** möchte ich der obere Teil des Headers auch sehen, wenn das Sitepanel angezeigt wird.

### Anforderungen
- Das Sitepanel soll der obere Teil des Headers nicht verdecken.

### Akzeptanzkriterien
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Verhalten des Headers beim Ausklappen des Sidepanels besprechen (Ab 13.00 Uhr)
- [x] Verhalten dokumentieren
   - TopBar (dunkelblau) soll immer noch sichtbar sein beim aufklappen des Sidepanels
   - Nach wie vor Header von oben nach unten sliden
- [x] Umsetzen
   - [x] Header Component aufsplitten
   - [x] Logik umbauen
   - [x] Smoke testen 
- [x] Review von @tuxmatta  anfordern
- [x] Mergen

**Comment by tobiasstern** [comment]
Test
