### ISSUE TITLE
Komponente zum unterscheiden ob Key Result Ordinal oder Key Result Metric

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#420]
Als **Kunde** möchte ich die Möglichkeit haben beim Erstellen oder Bearbeiten eines KeyResult zwischen Metrisch und Ordinal unterscheiden zu können. 

### Anforderungen
- Im Dialog zum erfassen eines Key Results soll ausgewählt werden können, ob es sich um ein ordinales Key Result oder um ein metrisches Key Result handelt
- Die entsprechenden Properties sollen via Restschnittstell an das Backend versendet werden.
- Beim wechseln der Komponente von Ordinal zu Metrisch soll falls der Benutzer bereits ausgewählt ist, dieser Ausgewählt bleiben. 

### Hinweis

![Image](https://github.com/puzzle/okr/assets/113369749/d43f0b55-8255-4f75-a4af-0d4b3e8290bd)

![Image](https://github.com/puzzle/okr/assets/113369749/a96e9923-98e1-4492-977e-f3ddeca15040)

- Das Layout, inklusive Styling ist im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=351%3A12257&mode=dev) ersichtlich. 

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Tab Reiter designen
- [x] Wechselmöglichkeit programmieren
- [x] Metrisch Seite
- [x] Ordinal Seite
- [x] Speichern in Form Group
- [x] Rückgabe der Werte mit @Output EventEmitter
- [x] Anzeigen für nicht Erlaubte Type Änderung
- [x] KeyResultDialog Standardwerte in FormGroup anpassen
- [x] Error font weight (manuel)
- [x] Remove mattabmodule in app.module
- [x] Mat inputs ersetzen
- [x] KeyResult Type style class aus css heraus
- [x] Regex auf nachkommastellen prüfen
- [x] Sonar skala unit zu number und nicht chf (manuel)
- [x] Number input auch negativ
- [x] Owner mat autocomplete
- [x] Werte auf Detail Card aktualisieren -> Wird durch side panel refactoring gelöst
- [x] Clean up code
- [x] Absprache mit UX 
- [x] Testing
- [x] Gegenseitiges Review
- [x] Änderungen nach dem gegenseiten Review
- [x] Tests fixen
- [x] Review

**Comment by lkleisa** [comment]
Das Ticket ist wie gefordert umgesetzt. Die Tests sind soweit vollzählig. Jedoch failen die Tests für den KeyResult-Dialog noch.

**Comment by ManuelMoeri** [comment]
- Sämtliches Changes die von Marc's review requested waren sind abgeschlossen.
- Der Code wurde an jeder möglichen stelle optimiert und kompakter gemacht.
- Der Code wurde geformatet und allgemeines cleanup wurde durchgeführt.
- Ein Migrationsskript für die Datenbank wurde geschrieben & Ausgeführt.

--> edoch Failen noch sämtliche Tests im "Keyresult-type" component. Scheint aber eher ein Problem mit dem Aufruf des Keyresultform.setValue zu sein als ein Fehler der Tests selber. Wäre gut wenn sich das jemand anschauen könnte.

Bei fragen bin ich in der Schule ab und zu auf dem Puzzle Chat online.

**Comment by lkleisa** [comment]
Meiner Änderungen in den Tests vom KeyResult Dialog wurden wohl überschriben, daher konnte ich alles nochmals machen. KR Type tests konnte ich nicht beheben, da ich die Implementation nicht verstehe
