### ISSUE TITLE
Drawer implementation

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#430]
Als **Kunde** möchte ich, falls ein Drawer geöffnet ist, dass der Header sauber in die Focustrap kommt. Filter sollen nicht mehr auswählbar sein und der Banner soll nicht verschwinden. 

### Anforderungen
- Der Banner liegt hinter einer sauberen Focustrap.
- Wenn der Banner auf der Overview ersichtlich ist, so verschwindet dieser nicht wenn der Drawer geöffnet wird. 

### Hinweis

- Zur Zeit verschwindet der Banner noch wenn ein Drawer geöffnet wird. 
- Zur Zeit ist noch keine sauber Focustrap wenn der Drawer geöffnet wird. 

### Akzeptanzkriterien
- [x] Die Ausgabe entspricht dem verlinkten Template. 
- [x] Schriften, Hintergründe, abstände und alle weiteren Stylings sind erfüllt. 
- [x] Angular Komponente und das Template sind mit Jest getestet
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] ???

**Comment by tobiasstern** [comment]
- [/ ] Topfender/Hauptmenu bleibt zugänglich bei offenem Sidepanel und ich kann z.b. das Benutzermenu anklicken
- [ ] Focustrap auf Header/Banner wo Filter hinkommen kann ich nicht testen, weil da zurzeit keine Elemente zum anklicken sind.
