### ISSUE TITLE
Only one call to /overview on load

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/okr#503]
**Describe the bug**
On reload multiple call are made to load the overview

**To Reproduce**
1. Reload page
2. Overview endpoint is called multiple times

**Expected behavior**
Only one call to /overview with the correct filter should be made

**Vorgehen**
- [x] Alle refresh data service calls aus filtern entfernen
- [x] In overview component auf router subscriben und wenn sich die query params ändern, die overview neu laden
- [x] Tests fixen
- [x] Tests nachziehen
- [x] Smoke testen
- [x] Rebasen
- [x] Review

**Comment by RandomTannenbaum** [comment]
- [ ] Write test to test filter overview component that filters out state of url params
- [ ] Fix loading of filters after login

**Comment by RandomTannenbaum** [comment]
**Stand Dienstag 31.10.2023:**
- Overview wird nur noch einmal aufgerufen, diese Funktionalität wurde also eingebaut
Dies wurde erreicht, indem die einzelnen filter-komponenten die overview nun nicht mehr reloaden, sondern die overview auf die activeRoute subscribed, und sobald sich diese ändert einen reload macht. Die Komponenten selber ändern nur noch die Query-Parameter in der URL.
- Allfällig kaputte tests wurden gefixt.

Was noch fehlt:
- Gründlich smoke testen (alle edge cases die die URL ändern, oder einen reload hervorrufen könnten) also objective erstellen, keyresult erstellen, check-in erfassen usw.
- Ein test wurde noch nicht fertig geschrieben den ich schon angefangen habe. Dabei geht es darum diese Logik im `overview copmonent` kurz zu testen:
- 

![Image](https://github.com/puzzle/okr/assets/109959802/508c6f79-e7ee-4f9f-bb8c-ed85dd7afec3)

Es soll also nicht neu geladen werden, wenn der query param state vorhanden ist, in der url. Den Test habe ich schon begonnen zu schreiben (letzter Test in overview.component.spec.ts), er funktioniert leider noch nicht.

- Testen ob invalide Werte aus den query parametern entfernt werden.

- Herausfinden warum werte die im Suchfenster eingegeben werden und ein Leerzeichen enthalten, das Leerzeichen in der URL als `%2520` codieren statt `%20`. @kcinay055679  fragen wenn nicht klar ist was gemeint ist, er kennt es. Hängt vermutlich damit zusammen, dass die url doppelt encoded wird?!

- Nach dem Login sind manchmal die Filter noch nicht korrekt vorgeladen. Sie laden dann erst nach dem reload. In firefox scheint dies für mich zu funktionieren aber in chrome nicht :(.

**Comment by ManuelMoeri** [comment]
Vorgehen:
- [ ] Ticket & @RandomTannenbaum's comment durchlesen
- [ ] Branch auschecken
- [ ] Verstehen was genau geändert wurde
- [ ] Gründlicher Smoke test
- [ ] Angefangener Test beenden
- [ ] Letze(r) Smoke Test(s)
- [ ] Code cleanup & format
- [ ] (Falls es nicht fertig wird aktuellen Stand dokumentieren)
- [ ] Reviewen
- [ ] Merge

**Comment by RandomTannenbaum** [comment]
**Things to resolve:**
- [ ] Wrong keyresult ids do not show an error toaster
- [ ] Filter laden nicht nach login
- [ ] Leerzeichen korrekt encoden
- [ ] Test if teams are updated when reload subject is called
- [ ] Query params are not preserved after login

**Comment by MarcEgliP** [comment]
# TODO:
- [ ] Ignorierte Tests fixen
- [ ] Gut Smoketesten
