### ISSUE TITLE
Resolve bugs in dialogs

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/okr#506]
**Describe the bug**
There are multiple bugs in ticket #499, fix them according to the expected behavior

**Expected behavior**

- [x]  Font color of errors should be  B3261B für Text und Border
- [x] Remove leading whitespaces in errors (after focus out)
- [x] Remove empty files (scss)
- [x] Remove all useless !important

~~"Check-in erfassen" radio buttons are not selectable by tab~~

**Comment by RandomTannenbaum** [comment]
Bugs found:
- [ ] To much space between description, quarters and buttons in create objective
- [ ] Team only loads after clicking on dialog in objective creation and editing
- [ ] Owner and unit in keyresult do not have an empty error
