### ISSUE TITLE
Team verwaltung

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#519]
Als Admin (org_gl) möchte ich die Möglichkeit haben in der Applikation Teams zu erstellen. Dazu möchte ich im Frontend im Header einen Button vorfinden, welcher mir dieses erlaubt.

### Anforderungen
- Alle Personen die der org_gl angehören, können im Frontend via Button im Header Teams erstellen
- Das Form zum Team erstellen erlaubt die Eingabe des Teamnamens und das zuordnen von mindestens einer, aber auch mehreren Organisationen. 
- Die organisationen werden aus dem Backend aus der Organisation Tabelle geladen, sofern diese den Status ACTIVE haben
- Falls ein Team eine Organisation zugeordnet hat, welche INACTIVE ist, wird diese im Frontend gekennzeichnet. 
- Für die GL ist neben dem Teamnamen im Fronten ein Editier Icon damit ein Bestehendes Team editiert werden kann 
- Das Backend erlaubt nur org_gl das erfassen von neuen Teams
- Mit einem migrationskript ist sichergestellt, dass alle bestehenden Teams die org_gl haben
- Alle CRUD operationen sind für die Team erstellt.
- Das anzeigen der Aktiven Obejctives wird entfernt

### Hinweise

- Der Dialog ist von UX nicht vorgegeben, wir implementieren einen Dialog, mit zwei Feldern ein Input Field und ein Dropdown

### Änderungen

_Änderungen am Ticket sind vorab mit Paco zu besprechen und hier festzuhalten_

### Akzeptanzkriterien
- [x] Die Story ist wie beschrieben umgesetzt
- [x] Es existiert genau ein Migrationsskript für das erstellen der Teams 
- [x] Alle CRUD Operationen für Teams sind unterstützt
- [x] Die Tests sind sowohl im Frontend wie auch im Backend erstellt
- [x] Im Frontend ist nur für die GL das erstellen des Teams möglich und ersichtlich 

#### Backend
- [x] Methode für die Rückgabe aller Organisationen schreiben
- [x] OrganisationController schreiben
- [x] Im OrganisationController call zu Service machen und alle Organisationen zurückgeben
- [x] DTO + Mapper für Organisation Entity anlegen
- [x] Edit im TeamController schreiben
- [x] Methode + Controller testen

#### Frontend
- [x] Button im Header implementieren
- [x] Dialog auf Buttonklick öffnen
- [x] Dialog (View) implementieren
- [x] Dialog Logik implementieren
- [x] Edit Icons neben Teams implementieren, welche den Dialog öffnen
- [x] Dialog testen

**Comment by MarcEgliP** [comment]
# Stand des Tickets
- [ ] Backend für das GET der Organisations ist implementiert, nur GL hat darauf Zugriff
- [ ] Icon für das Öffnen des Dialogs im ApplicationHeader ist implementiert und öffnet auf Knopfdruck den Dialog
- [ ] Service für die Organisationen steht im Frontend bereit
- [ ] Organisations werden in Dropdown geladen, Dropdown und Inputfeld sind gestyled
- [ ] Erster test für den Controller ist geschrieben

# Was gemacht werden muss
- [ ] SubmitButton einbauen und disablen wenn Form invalid ist
- [ ] PostRequest im Backend implementieren
- [ ] PostRequest über den OrganisationService im Frontend ansprechen
- [ ] Frontend (Dialog) testen
- [ ] Backend testen

**Comment by MarcEgliP** [comment]
# Aktueller Stand
 Das Ticket ist bei @tuxmatta in Review
