### ISSUE TITLE
Header Styling

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#571]
Als User möchte ich ein konsistentes Styling über die gesammte Applikation.

### Anforderungen
- [x] Schriftgrösse in den Chips ist noch zu klein
- [x] Die Zahl für active Objectives soll entfernt werden
- [x] Lupe sollte keinen Randd zum Suchfeld haben
- [x] Lupe ist noch zu gross 
- [x] Header soll die Mobile ansicht erfüllen
- [x] Mit Ux die Reihenfolge der Quartale absprechen und entsprechend implementieren -> Wurde mit Simu abgesprochen reihenfolge soll Zukünfig, Aktuell und alle vergangenen Sein aber das Aktuelle als Default ausgewählt. Ausserdem möcht er ein Label beim Aktuellen haben
- [x] Gerundete Eingabefelder haben in den Ecken noch einen weissen Hintergrund
- [x] Abstand zwischen Teamverwaltung, Help Icon und User Menü sollte auf Desktop & Mobile geprüft und vereinheitlicht werden
- [x] Bei der mobilen Ansicht des Headers, ist oben noch ein zu grosser abstand, da eventuell Quartal als Label stehen
- [x] Der Kontrast wenn ein Item aus der Top bar im Fokus ist, ist noch zu klein daher einen Rahmen um das Icon ziehen

### Akzeptanzkriterien
- [x] Die oben genannten Fehler sind behoben
- [x] End To End Tests stellen ein konsistentes Layout sicher
- [x] Smoketests wurden gründlich durchgeführt
- [x] Unittests wurden angepasst
- [x] Unnötiger Code wurde entfernt

### Vorgehen
- [x] Diese Punkte müssen angepasst werden:
    - [x] Schritgrösse mit Simu absprechen -> Wurde gemacht kann man so lassen
    - [x] Zahl der Objectives & die Methode dafür im Front- und Backend löschen
    - [x] Rand der Lupe entfernen
    - [x] Lupe verkleineren -> Mit Simu schauen
    - [x] Minder's header testen
    - [x] Labels bei der Reihenfolge der Quarters hinzufügen
    - [x] Weissen hintergrund bei den Ecken entfernen [(Link)](https://markheath.net/post/keep-inside-rounded-corners-css)
    - [x] Abstand bei User und Help Icon im Header vereinheitlichen
    - [x] Den zu grossen Abstand bei der Modbilen Ansicht des Headers entfernen und eventuell Label hinschreiben
    - [x] Kontrast mit Weissen Rahmen in der Top bar erhöhen
    - [x] OKR Logo durch korrektes SVG ohne riesigen Abstand ersetzen
- [x] Tests fixen
- [ ] Review & Changes
- [ ] Merge

**Comment by ManuelMoeri** [comment]
**Stand 22.11.2023**

Ich habe alle Anforderungen die oben Stehen erfüllt und habe mich Oft mit Simu ausgetauscht um Unklarheiten zu beseitigen. Hier sind die Punkte die sich Konkret geändert haben:
- Die Zahl für die Aktiven Objectives wurde aus dem Front- und Backend entfernt.
- Der Objective Filter und die Lupe nebenan haben jetzt dort wo si sich berühren eckige Ecken sprich die Ecken sind nicht mehr abgerundet.
- Die Lupe wurde ausserdem verkleinert.
- Für die Mobile ansicht wurde das OKR SVG oben mit einem neuen ersetzt das gleich aussieht aber nicht so einen riesigen Leerraum auf der rechten Seite hat. 

Zum darstellen:
Altes SVG das noch auf Staging ist:
![image](https://github.com/puzzle/okr/assets/109959820/cdbda2dd-8f10-4fdb-8f0e-61c986028a0b)

Neues SVG:
![image](https://github.com/puzzle/okr/assets/109959820/508d033f-b2f5-4ec2-bf62-d38e716e67ba)

- Die Reihenfolge der Quarter wurde angepasst und jetzt werden sie einfach nach Datum Sortiert aus der DB geholt. Das heisst das das Zukünftige zuoberst ist und das Aktuelle an zweiter Stelle. Jedoch wird als Default immer noch das Aktuelle also das Zweite ausgwählt. Ausserdem hat das Aktuelle Quartal jetzt ein zusätzliches Label mit " Aktuell". Das dieses Label platz hat wurde die Breite des Quarter Filters minimal erhöht. Ausserdem habe ich zu den Quarters im Front- und Backend Tests gefixt.
- Die Weissen ecken im Hintergrund der Filter wurden entfernt.
- Der Abstand zwischen Teamverwaltung, dem Hilfe button und dem User Menü wurde vereinheitlicht und verringert.
- Bei der Mobilen Ansicht steht jeztzt "Filter" wenn man den Header aufklappt.
- Kontrash im Header wurde durch einen Rahmen on hover erhöht.

Alle Unit Tests laufen korrekt. Die E2E Tests nicht, aber mir wurde gesagt das dies auch auf Main der Fall ist.

### Was muss noch gemacht werden?
Grundsätzlich ist alles Fertig und sogar schon mit Simu angeschaut. Falls beim Review noch Codemängel auftauchen müssen diese Behoben werden.

### Bei fragen
- Schreiben
- Anrufen
- usw
