### ISSUE TITLE
Button Styling

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#573]
Als User möchte ich ein konsistentes design über die gesammte Applikation.

### Anforderungen
- [x] Buttons haben alle die gleiche Struktur
- [x] Buttons mit einem "+" haben dieses sauber mit dem Text aligned
- [x] Der Abstand zwischen Buttons ist überall der gleiche
- [x] Buttons haben alle das selbe Padding auch beim Hovern
- [x] Die Farbe beim Hovern über einen Button ist überall blau

### Akzeptanzkriterien
- [ ] Die oben erwähnten Fehler sind alle behoben
- [ ] End To End Tests stellen sicher, dass das Layout einheitlich ist
- [ ] Smoketests wurden gründlich durchgeführt
- [ ] Unit Tests sind falls notwendig angepasst.

### Vorgehen
- [x] Folgende Buttons sollten auf die obigen Punkte überprüft werden
  - [x] Key Result / Objective hinzufügen
  - [x] Team erstellen / bearbeiten
  - [x] Objective bearbeiten / duplizieren / abschliessen
  - [x] Key Result bearbeiten
  - [x] Check-in erfassen
  - [x] Alle Check-ins anzeigen
- [x] Review von Yanick
- [ ] Review
- [ ] Merge
### Bemerkungen
Das Padding wurde bei allen Button mit einer Hintergrundfarbe oder einer Umrandung auf 16px überschrieben. z.B. der "Speichern" Button. Alle Buttons die keine Umrandung / Hintergrundfarbe haben, z.B. "Key Result Hinzufügen" oder "Abbrechen" haben ein Padding von 8px. -> Wurde von UX approved.

**Comment by ManuelMoeri** [comment]
**Stand 29.11.2023**

Das Ticket ist fertig. Es ist im Review und wenn noch sachen im Review auftauchen müssen diese noch gefixt werden.

Der "Objective hinzufügen" Button wurde nicht vereinheitlich da dies im Ticket [#610](https://github.com/puzzle/okr/issues/610) behandelt wird. Ich habe dieses Ticket übernommen und das Styling genau gleich wie hier umgesetzt.
