### ISSUE TITLE
Fokus Styling

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#577]
Als User möchte ich überall den gleichen Flow durch die Applikation haben.

### Anforderungen
- [x] Wenn ein Dialog geöffnet ist, so ist der Fokus initial auf dem Close Button
- [x] Die Tabs für Metrisch/Ordinal im Key Result haben nicht den Richtigen Fokus
- [x] Actionplan muss mit der Tastatur bedient werden können.

### Akzeptanzkriterien
- [x] Die oben genannten Fehler sind behoben
- [x] End To End Tests sind ergänzt 
- [x] Smoketests wurden gründlich durchgeführt
- [x] Unit tests sind ergänzt

### Vorgehen
- [x] Dialoge überprüfen, wo der Fokus noch nicht initial auf dem Close Button ist
- [x] Tabs für das Metrisch/Ordinal fixen

**Comment by MarcEgliP** [comment]
#Aktueller Stand

- Fokus Styling für das Toggeln des KeyReslut Types wurde gefixed und mit UX abgesprochen
   -> UX hat die aktuelle Implementation approved
- Actionplan wurde tabbable gemacht, besitzt jedoch noch ein paar Bugs, welche im folgenden aufgelistet werden

#Was  gemacht werden muss
- [ ] Bugs in Actionplan lösen: 
   -> Wenn man in ein Inputfeld Text eingibt und dann weitertabben will, muss man 2x tabben um aufs nächste Inputfeld zu gelangen
   -> Wenn man alle Actions löscht und eine neue hinzufügt wird in der Konsole ein Error geworfen
- [ ] Der Button um eine Action zu löschen muss ebenfalls tabbable gemacht werden
- [ ] Tests durchschauen => Es muss überprüft werden ob alle Tests noch laufen, die jenigen welche failen müssen gefixed werden
