### ISSUE TITLE
Scoring Styling

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#578]
Als User möchte ich ein konsistentes Layout über die gesammte Applikation.

### Anforderungen
- [x] Pattern wenn Stretch Goal erreicht wird soll dem neuen Pattern im Figma entsprechen 
- [x] Manchmal ist bei einem Ordinalen Key result ein doppelter Strich am ende des 
- [x]  Manchmal ist bei einem metrischen Key Result ein doppelter Strich am Ende oder am Anfang des jeweiligen Sektors

### Hinweise
- Das Pattern findet ihr im Figma: https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=1799%3A19301&mode=dev

![Image](https://github.com/puzzle/okr/assets/113369749/ef6536cb-5dd5-4465-a946-426854a21b76)

### Akzeptanzkriterien
- [x] Die oben genannten Fehler sind behoben
- [x] End to End Tests stellen das Layout sicher
- [x] Smoketests wurden gründlich durchgeführt 
- [x] Unit Tests sind ergänzt 

### Vorgehen
- [x] Pattern des Stretch Goals wechseln
- [x] Strich am Ende untersuchen
- [x] Wenn möglich und Ursache gefunden, Fehler beheben
- [x] Rebasen, Files reviewen
- [x] Review von @peggimann anfordern

**Comment by MarcEgliP** [comment]
# Aktueller Stand
- [ ] Der Border rechts wurde entfernt
- [ ] Es wird auf UX und den neuen Entwurf für das SVG gewartet
