### ISSUE TITLE
Dialoge auf mobile

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#624]
Wenn ein Dialog auf mobile Ansicht geöffnet wird ist der Abstand zum Rand zu hoch. 
Die Dialoge haben neu im CSS eine max-height gesetzt bekommen. @lkleisa hat eine Umsetzung vorher gemacht, wie es ohne funktioniert hat. 

Es gibt bereits [einen PR](https://github.com/puzzle/okr/pull/780), diesen zuerst ansehen und wenn nötig erweitern

### Anforderungen
- Die Dialoge auf Mobilen Devices entspricht dem [Figma](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=3141-3856&t=HJRRh2ZmSQTaARyv-4)
- Die Trennlinie für den Scrollbaren bereich ist ebenfalls in der Webversion erstellt
- Das Verhalten ist auf allen Browsern das gleiche (Edge, Firefox, Safari)

### Akzeptanzkriterien
- [x] Dialoge sind angepasst gemäss Anforderungen
- [x] Tests sind geschrieben
- [x] UX hat das feature gereviewd

**Comment by kcinay055679** [comment]
In Safari werden die Buttons der Dialoge abgeschnitten.

![Image](https://github.com/user-attachments/assets/78ed1530-6f21-4329-87b5-3bcf13b60f94)
Um das zu testen kann [Browserstack](browserstack.com) verwendet werden. Browserstack ist nicht nur ein Simulator sondern verwendet echte Geräte welche gemirrored werden. Zusätzlich unterstützt Browserstack auch das Verbinden mit dem eigenen System damit kann sogar auf  localhost zugegriffen werden.

**Comment by kcinay055679** [comment]
- [ ] unify `CancelDialog` and`ConfirmDialog`
- [ ] Check if all dialog should have height 100% on mobile
- [ ] Adjust styling of dialogs to [Figma]([igma](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=3141-3856&t=HJRRh2ZmSQTaARyv-4))
