### ISSUE TITLE
Entwicklerversion: state + session_state nach Login verhindern ein Site-Refresh

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#636]
**Describe the bug**
Die Entwicklungsversion verhaltet sich nach dem Anmelden anders als die Test-Version:
Nach der Anmeldung beinhaltet die URL die `state` und `session_state` Information. Diese verbleibt in der URL während dem Arbeiten.
Nach einem Site-Refresh (zB: F5) führen diese beiden Informationen dazu, dass die WebApplikation nicht mehr erfolgreich initialisiert und es wird ein leerer Screen angezeigt.

**To Reproduce**
1. Neu anmelden.
2. `F5` drücken

Beim `F5` werden die `state` und `session_state` Information aus der URL entfernt. Aber die Seite erholt sich nicht mehr, bis man die SiteDaten löscht.

#### Solution
Eventuell könnte man nach dem erfolgreichen Anmelden die Information aus dem URL entfernen, falls vorhanden.

![Image](https://github.com/puzzle/okr/assets/4771882/be439f4e-7261-4833-ac7d-eece479cd009)

**Comment by peggimann** [comment]
Wurde bereits implementiert.
