### ISSUE TITLE
Icon beim Toaster

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#699]
Teilweise wird das Icon vom Toaster nicht korrekt angezeigt. 

### Anforderungen
Wenn ein Toaster eingeblendet wird, muss das Icon auch eingeblendet werden.

### Akzeptanzkriterien
- [x] Die Icons zu den Toastern werden immer angezeigt
- [x] Die Funktionalität ist sauber mit Smoketests sichergestellt.

**Comment by RandomTannenbaum** [comment]
**Stand 15.01.2024**
Die SecurityConfig wurde erweitert, konnte aber noch nicht getestet werden, da die pipeline noch nicht lokal läuft.
