### ISSUE TITLE
Commit Zone ab 0.3

### ISSUE THREAD

**Issue by bsantschi** [puzzle/okr#703]
Meiner Meinung nach dürften wir ab 0.3 in der Commit und nicht mehr Fail Zone sein.

Beispiel:
https://okr.puzzle.ch/keyresult/138?teams=14

![Screenshot 2023-12-12 at 15 15 25](https://github.com/puzzle/okr/assets/108862416/9fb4cade-4b58-43f2-8e8b-983492d49376)

@PippoLeimgruber wie siehst du das?

**Comment by lkleisa** [comment]
Lieber Bruno
Deine Verbesserung wurde umgesetzt und du findest nun den gelben Commit Balken ab 0.3 und den grünen Target Balken ab 0.7. Melde dich bei Fragen oder weiteren Rückmeldung. 
Herzlich, dein OKR Team.

**Comment by bsantschi** [comment]
Merci viu mau, Lias!
