### ISSUE TITLE
OKR Benutzerverwaltung

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#704]
Als Endbenutzer möchte ich eine Benutzerverwaltung im Tool haben. Dabei möchte ich User einem Team zuordnen können und den Benutzern entsprechend rechte geben. 

![Image](https://github.com/puzzle/okr/assets/17762787/fdf34a0c-5c9f-4160-9dd7-ec24a24930bc)

### Anforderungen
- JWT reicht entweder SSO von Mandant oder Keycloak von Puzzle das JWT muss folgendes Enthalten:
    - Welcher Mandant
    - Vorname
    - Nachname
    - Email
- Username ausbauen und Email als unique halten in der Datenbank
- Ein Benutzer kann verschiedene Rechte haben nur OKR-Champion oder normal, auf dem Team existiert ein Team Admin.
- Es Existiert eine Team/User Tabelle, welche zusätzlich eine Team-Admin Flag hat.
- Jeder kann ein Team erstellen und User seinem Team hinzufügen. 
- Jeder User kann bei allen Teams denen er angehört OKR im Draftstatus einsehen
- Jeder User kann alle publizierten OKR von allen Teams einsehen. 
- OKR-Champion können immer alle OKR sehen auch Draft von Teams, welchen er nicht angehört.
- Ein Benutzer kann einem oder mehreren Teams zugeordnet werden. 
- Migrationsskript für die User => wird in #740 umgesetzt

**Comment by janikEndtner** [comment]
Weitere Punkte:

- Jedes Team muss mindestens ein Admin haben

**Comment by janikEndtner** [comment]
**E2E Tests**

OKR Champion

1. Login als OKR Champion
2. Navigieren zu Benutzerverwaltung
3. Navigieren zu Profil von Benutzer X
4. Einladen von Benutzer X zu Team 1 als Team Admin => Prüfen in Team Liste
5. Einladen von Benutzer X zu Team 2 als Team Member => Prüfen in Team Liste
6. Prüfen in alle Teams Liste, ob Benutzer X richtige Rollen hat
7. Ausloggen

Benutzer X

9. Einloggen als Benutzer X
10. Prüfen ob Team Filter auf Team 1 und Team 2 gesetzt sind
11. Prüfen, ob Drafts von Team 1 und Team 2 gelesen werden können, aber nicht von Team 3 (ist dies schon durch anderen Test abgedeckt?)
12. Profil von Benutzer X öffnen => Prüfen ob richtige Rollen gesetzt
13. Zu Team 2 navigieren => Prüfen ob nichts editiert werden kann
14. Zu Team 1 navigieren
15. Name von Team 1 wechseln
16. Auf "Members hinzufügen" klicken
17. Nach Benutzer Y suchen, klicken (noch nicht hinzufügen)
18. Nach Benutzer Z suchen, klicken (noch nicht hinzufügen)
19. Benutzer Z wieder von der Liste entfernen
20. Hinzufügen
21. Auf Profil von Benutzer Y navigieren => Prüfen ob "Zu weiterem Team hinzufügen" deaktiviert ist
22. Auf Teamseite navigieren, Benutzer Y löschen => Prüfen, ob Teamseite Benutzer Y nicht mehr enthält
24. Auf Profil von Benutzer Y navigieren
25. "Zu weiterem Team hinzufügen" => Prüfen, ob nur Team 1 als Auswahl kommt
26. Benutzer Y zu Team als Admin hinzufügen
27. Teamrolle von Benutzer Y zu Team Member wechseln
28. Teamrolle von Benutzer Y löschen
29. Auf Teamseite navigieren => Prüfen ob Teamseite Benutzer Y nicht mehr enthält
30. Ausloggen

OKR Champion

1. Einloggen
2. Zu Teamseite navigieren
3. Zu Team 1 navigieren
4. Benutzer X löschen
5. Zu Team 2 navigieren
6. Benutzer X löschen
