### ISSUE TITLE
Geschäftsjahr

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#706]
Als Mandant möchte ich bestimmen können, wann mein Geschäftsjahr beginnt. 

### Anforderungen
- Mittels application properties (oder ENV Variable) kann eingestellt werden, welcher Monat der Startmonat vom Geschäftsjahr ist (Bei Puzzle ist es z.B. der Juli)
- Das Label des Geschäftsjahrs muss entsprechend formatiert werden:
    - Bei Startmonat Juli wäre das Label des ersten Quartals GJ 23/24-Q1, das Startdatum 2023-07-01 und das Enddatum 2023-09-30
    - Bei Startmonat Januar wäre das Label des ersten Quartals GJ 24-Q1, das Startdatum 2023-01-01 und das Enddatum 2023-03-31
- Der Scheduler soll weiterhin so bleiben, dass vier Monate vor dem Start des neuen Quartals dieses automatisch erstellt wird (siehe QuarterBusinessService#generateQuarter)

siehe [Konzept](https://files.puzzle.ch/apps/files/?dir=/OKR/customizing&openfile=5984609) Kapitel 2.3

**Comment by gobeli** [comment]
Implementiert mit #865. Die Konfiguration kann wie im Konzept beschrieben über die application properties vorgenommen werden.
Im Moment gibt es noch ein unschönes Verhalten, wenn 1 (Januar) als Startmonat konfiguriert ist. Mit dem default Format gäbe das als Output z.B. für Januar-März 2024 `GJ-24/25-Q1` Obwohl das Geschäftsjahr nicht bis ins 2025 gehen würde. Workaround ist im Moment das Format so anzupassen, dass dies keine Rolle spielt z.B. `GJ-xx-Qzz`
