### ISSUE TITLE
Wichtigste Styles pro Mandant konfigurierbar machen

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#708]
Als User möchte ich die wichtigsten Styles pro Mandant konfigurierbar machen können.

### Anforderungen
- Logo kann selber bestimmt werden
![Image](https://github.com/puzzle/okr/assets/17762787/ebe6a6c6-ecc2-448d-8dcc-8c74b110c0b3)
- Titel und Favicon muss bestimmt werden können
![Image](https://github.com/puzzle/okr/assets/17762787/fcd89e88-7552-4f19-9dd6-0ddabdfd7c1d)
- Diese Konfigurationen können über die Application Properties gemacht werden (später wird es unterschiedliche Application Properties pro Mandant geben)

siehe [Konzept](https://files.puzzle.ch/apps/files/?dir=/OKR/customizing&openfile=5984609) Kapitel 2.5

**Comment by janikEndtner** [comment]
Ausserdem soll Primary Color definiert werden können (material-palette)

**Comment by Makae** [comment]
Hallo Zusammen,
ich habe die Anpassungen vorgenommen.

Neu gibt es application properties um zu customizen:
```
// application.properties
okr.clientconfig.favicon=assets/favicon.png
okr.clientconfig.logo=assets/images/okr-logo.svg
okr.clientconfig.title=Puzzle OKR

// application-staging.properties
okr.clientconfig.customstyles.okr-topbar-background-color=#ab31ad
```

Mit `okr.clientconfig.customstyles.<css-variable-name>` können mandaten-spezifische css variablen gesetzt werden. Das wird hier verwendet um auf der staging umgebung die top-bar einzufärben.

Im Konzept dokument waren noch mehr Anforderungen, die sich nicht komplett mit denjenigen in dieser Story decken. Mit der css-variablen lösung kann man das aber sehr einfach ergänzen.


**Beispiel**
![Image](https://github.com/puzzle/okr/assets/5574404/20a53b2e-ddbb-42bf-950a-f4bebfd8e94d)

**Comment by Makae** [comment]
PR ist nun "ready for rewiew":
https://github.com/puzzle/okr/pull/868
