### ISSUE TITLE
Mandantenfähigkeit aufsetzen

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#709]
Wir haben grundsätzlich zwei verschiedene Möglichkeiten, die Applikation mandantenfähig zu machen:

1. Wir erstellen für jeden Mandanten eine eigene Instanz. Diese ist unter einer spezifischen subdomain deployed, z.B. siemens.okr.ch und aareguru.okr.ch
    * Wir gehen davon aus, dass diese Variante grundsätzlich teuerer ist, weil es eine separate Datenbank und jeweils eine separate Instanz gibt. Es müsste aber abgeklärt werden, ob dies stimmt oder nicht. Allenfalls könnte man mit Hitobito schauen, wie dort die Mandantenfähigkeit gelöst ist
    * 
2. Wir trennen die Datenbanken auf Applikationsebene und befolgen die Anleitung nach https://www.baeldung.com/multitenancy-with-spring-data-jpa
    * In diesem Fall könnten wir grundsätzlich alle Mandanten unter okr.puzzle.ch laufen lassen. Wir haben aber das Problem, dass wir irgendwie unterscheiden müssen, an welches Loginsystem redirected wird.
    * Diese Variante führt zu etwas mehr Komplexität der Applikation selber

In diesem Task geht es darum, herauszufinden, welches die bessere Variante ist und diese dann zu implementieren.

**Comment by janikEndtner** [comment]
Wir haben uns aus Kostengründen dafür entschieden, die zweite Variante umzusetzen. 
Offen ist noch, wie SSOs verschiedener KMUs angebunden werden können und was geschieht, wenn das KMU kein eigenes SSO hat. In diesem Fall müssen wir etwas anbieten.

**Comment by clean-coder** [comment]
Mandantenfähigkeit ist umgesetzt und im `main` Branch.
