### ISSUE TITLE
URL auf Hilfeseite

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#710]
Als Kunde möchte ich die Möglichkeit haben, auf meine eigene Hilfeseite zu verlinken 

### Anforderungen
- Der Link für den Hilfebutton kann von jedem Kunde Selber bestimmt werden
 -  <del>Erklärungen zum Tool werden im Tool selber gemacht und präsentiert --> Absprache mit UX wo werden hilfe Icons verwendet? Wie sieht die Hilfeseite aus? </del>
- <del>Eventuell mit Tooltip Bubbles arbeiten falls notwendig.</del>

**Comment by clean-coder** [comment]
URL auf Hilfe Seite in den applicaiton.properties im Backend (in der tenant Section) definieren und dem Client verfügbar machen.

**Comment by nevio18324** [comment]
### Todo's ###

- [ ] add var in der Config für die url der Hilfseite
- [ ] die var im Frontend einbinden
