### ISSUE TITLE
Letzter Wert bei Check-in Metrisch anzeigen

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#728]
Als User möchte ich den letzten erfassten Wert eines metrischen Key Results beim Check-in auf dem Key Result sehen. 

### Anforderungen
- Neben dem Eingabefeld "Neuer Wert" soll der Wert des Letzen Check-ins angezeigt werden. 
- Der Wert ist in einem grauen Anzeigefeld angezeigt
- Bei der mobilen Ansicht soll der Letzte Wert oberhalb des Eingabefelds dargestellt werden

### Akzeptanzkriterien
- [x] Die Anforderungen sind erfüllt
- [x] Smoketests wurden gründlich durchgeführt
- [x] E2E-Tests sind ergänzt 
- [x] Unit und Integration Tests sind ergänzt

**Comment by MarcEgliP** [comment]
# Stand des Tickets
=> Ticket wurde umgesetzt, Pullrequest ist gestellt und gerebased:

# Zu erledigen
- [ ] In Review mit @peggimann das Verhalten der Breakpoints besprechen
