### ISSUE TITLE
Icons Header

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#729]
Die Icons in der Top Bar sind noch nicht stimmig. 

### Anforderungen
- Die Icons haben die selbe Höhe wie ein Grossbuchstaben
- Die Icons sind genau mit den Grossbuchstaben Alligned
- Die Icons haben alle den selben Abstanz zur Schrift

### Anforderungen
- [x] Die Anforderungen sind erfüllt
- [x] Smoketests wurden gründlich durchgeführt
- [x] E2E-, Unit und Integration Tests sind wo nötig angepasst

**Comment by kcinay055679** [comment]
![icons-aligned](https://github.com/puzzle/okr/assets/79108296/b42d559e-0470-42e2-acec-d2e025b75e3d)
Icons are now aligned
