### ISSUE TITLE
Schriftart unterschiedlich je nach Browser

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#730]
Je nach Browser verwendet das OKR-Tool andere Schriftarten

### Anforderungen
- Die Fonts werden von der Applikation bereitgestellt
- Die Fonts sind immer dieselbe auf allen Browsern und geräten 
- Die Fonts sind so implementiert, dass keine Fallbackfonts verwendet werden
- Das Gewicht der Font ist wie vorher

### Akzeptanzkriterien
- [x] Die Anforderungen sind erfüllt
- [x] Smoketests sind gründlich durchgeführt
- [x] E2E-Tests stellen sicher, dass die korrekten Fonts verwendet werden

**Comment by kcinay055679** [comment]
The font is applied to both browsers (Chrome, Firefox).
E2E tests are written but since they run only on chrome the behaviour for firefox isnt't secured.
Although the font gets applied correct on  firefox the font weight is always 400

**Comment by kcinay055679** [comment]
I added the font in diffrent formats (ttf, woff, woff2) and in combination with the property "display-font:swap" any browser should always be able to use one of the provided fonts.
