### ISSUE TITLE
Icon für Ongoing Objectives

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#732]
Als User möchte ich eine klare Darstellung vom Status meiner Objectives

### Anforderungen
- Ein Objectives welches Ongoing ist soll anstelle eines blauen Punktes ein Icon haben, welches WIP darstellt.
- Abklären mit UX welches Icon dazu passt. 
- Evt Chartlinie ?

### Akzeptanzkriterien
- [x] Die Anforderungen sind alle erfüllt
- [x] Smoketests wurden gründlich durchgeführt
- [x] E2E-Tests sind angepasst.

**Comment by kcinay055679** [comment]
Simu hat uns diese Icon zur Verfügung gestellt:
https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351%3A11886&mode=design&t=5JHglXOxZYFQ3XcA-1
