### ISSUE TITLE
Such Icon grösse

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#734]
Als User möchte ich ein balanciertes Design haben. 

### Anforderungen
- Mit Ux abklären welche grösse die Such-Lupe beim Suchen nach Objectives haben soll
- Die gewünschten Änderungen implementieren

### Akzeptanzkriterien
- [x] Die Anforderungen sind erfüllt
- [x] Smoketests wurden gründlich durchgeführt
- [x] Falls notwendig sind die Tests angepasst

**Comment by kcinay055679** [comment]
Ich habe ds Icon an das Figma angepasst und warte noch auf bestätigung von ux.

**Comment by kcinay055679** [comment]
Die aktuelle Variante wurde von UX abgesegnet
