### ISSUE TITLE
OKR-Renovate PR

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#742]
Als Entwickler möchte ich dass die Applikation immer auf dem aktuellen Stand ist, damit keine ungewollten Security Issues entstehen. 

### Anforderungen
- Die PullRequests von Renovate sind überprüft 
- Die PRs von Renovate sind gemerged.

**Comment by kcinay055679** [comment]
Alle Prs des Renovate Bots sind gemerged. Mir ist noch aufgefallen das der Dependabot noch ein Security Issue anzeigt, dies kann aber nicht behoben werden bis Angular eine update für das package  "@angular-devkit/build-angular" veröffentlicht welche das Problem löst
