### ISSUE TITLE
[Infra]Keycloak instanz bestellen + konfigurieren

### ISSUE THREAD

**Issue by Makae** [puzzle/okr#752]
* Instanz wird auf OpenShift als container deployed
* Instanz brauch anbindung an eine PGSQL db um die daten zu persistieren
* Für unsere DEV-Umgebung:
  * Keinen IdP Broker
  * Einfach direkt 2 Realms registrieren für 2 kunden (pitc + siemens)
  * Über hosts file die subdomains registrieren
  * Anpassungen an SpringBoot und Angular security configs, damit sie mit der neuen Subdomain zurecht kommen

**Comment by janikEndtner** [comment]
Wir binden die SSOs direkt über die Applikation, nicht über das Keycloak an. Siehe https://files.puzzle.ch/apps/files/?dir=/customizing&openfile=6086766
