### ISSUE TITLE
Korrekturen aus Testing

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#789]
- Wording für "Team hinzufügen" zu "Team erfassen" anpassen
- In der Teamverwaltungs-Seite sollte im Header auch ein Button "OKR Übersicht" dargestellt werden - analog zu "Teamverwaltung" wenn man in der OKR-Übersicht selber ist
- Members zu Team hinzufügen:
    - "entfernen" button sieht komisch aus mit weissem 
    - "Puzzle-Abfalleimer" verwenden
- Team + Member suche: User sollte "Member" heissen

**Comment by Makae** [comment]
UAT mit Philipp

Allgemein:
* Sollen wir das wording für "Team hinzufügen" zu "Team erfassen" oder so anpassen?
  * Auch sollten wir es Einheitlich machen im allgemeinen
* Sind die Schriftarten beim "Team Erfassen" dialog korrekt?
* In der Teamverwaltungs-Seite sollte im Header auch ein Button "OKR Übersicht" dargestellt werden - analog zu "Teamverwaltung" wenn man in der OKR-Übersicht selber ist 

Alle Teams:
* Spalte "Rolle" sollte man eigentlich nicht sehen, da man in unterschiedlichen Teams unterschiedliche Rollen haben kann

Team Liste + Alle Teams:
* Icon des Benutzers anpassen, wenn man OKR-Champion ist (Oder hinter den user Namen "(OKR-Champion)")

Edit User:
* Tooltip "Zu weiterm Team hinzufügen" sinnvoller machen?
* Text "Zu weiterm Team hinzufügen" macht nicht sinn, wenn man noch keinem Team zugehörig ist
* Wording "OKR-Champion: JA" wirk ein bisschen komisch
  * -> Eventuell untschiedliche Icons für die Rollen, oder ob OKR-Champion (Ausgefülltes Manöggeli, oder Manöggeli mit Hut)

Add member to team:
* Members zu "Feel good team" hinzufügen 
  * -> "entfernen" button sieht komisch uas mit weissem padding
  * -> "Puzzle-Abfalleimer" würde evtl mehr sinn machen
* Name für "Team-Admin" Rolle eventuell umbenennen? 
  * -> Evtl. nur "Member" + "Admin" anstatt "Team-*"
* Man möchte eigentlich gerne Members hinzufügen können, welche sich noch nicht angemeldet haben


Team + Member suche;
* Users sollte "Member" heissen

**Aufgekommene Fragen**
F: Wie kommen die Benutzer in die Liste unter "Alle Teams"?
A: Sobald sich die Benutzer über ihren IdP anmelden, erscheinen sie automatisch in der Liste
