### ISSUE TITLE
Objective bearbeiten: Quartal stimmt nicht.

### ISSUE THREAD

**Issue by tuxmatta** [puzzle/okr#792]
**Describe the bug**
Habe ein Fehler auf INT gefunden, welcher wahrscheinlich auf auf PROD ist:

Möchte man ein Objective bearbeiten, zeigt die Maske nicht das richtige Quartal an und beim Speichern kommt die Warnung: "Das Objective kann nicht in ein anderes Quartal verlegt werden."

**To Reproduce**
1. OKR-Tool ohne Quartalsinfo im URL öffnen: https://okr-stag.ocp.cloudscale.puzzle.ch/
2. Ein bestehendes Objective editieren
3. Das Formular hat nicht das Quartal vom Objective eingestellt, sondern wahrscheinlich das erste in der DropDown-Liste (OKR-Tool-Fehler-1.png)
4. Lässt man die Einstellung so, so zeigt es beim Speichern die beschriebene Warnung an. (OKR-Tool-Fehler-2.png)

![OKR-Tool-Fehler-1](https://github.com/puzzle/okr/assets/4771882/9cff087c-85fd-4ea1-be4f-5498dd4d3dbe)
![OKR-Tool-Fehler_2](https://github.com/puzzle/okr/assets/4771882/16ac74c4-d6c3-4152-892f-26328eda2b7f)

**Comment by Miguel7373** [comment]
### Stand 21.10.2024

Ich habe das problem mit einem currentquarter und bei editieren des objective mit dem quarter des objectives gelöst. Allerdings geht der test dazu dann nicht mehr da das quarter mit der id 0 zurückkommt deswegen habe ich nun auf dem branch  [Get current quarter from backend #1039 von dem ticket 9](https://github.com/puzzle/okr/pull/1039) von dem ticket https://github.com/orgs/puzzle/projects/3/views/1?pane=issue&itemId=61316888&issue=puzzle%7Cokr%7C902 versucht dies zu beheben indem ich die provider mid test ändere damit das resulat dann richtig ist. Doch dies geht noch nicht.

**Comment by RandomTannenbaum** [comment]
**Stand 22.10.2024**
Ich habe heute vor allem daran gearbeitet die Tests wieder zum Laufen zu bringen. Im Endeffekt hat sich das Problem als sehr simpel herausgestellt.

Im Test haben wir auf dem select Element `dispatchEvent(new Event('input'))` ausgeführt. Wir haben das quarter zwar vorher im select Element gesetzt, aber der Wert wurde nicht in der `FormGroup` persitiert, da dies anscheinend erste passiert, wenn ein `change` event erkannt wird. Der Fix war also einfach das Event von `input` auf `change` geändert.

**Comment by RandomTannenbaum** [comment]
**Stand 23.10.2024**
Ich habe heute noch einmal über die PR geschaut und das resolved was mir gerade aufgefallen.

Einen kleinen comment habe ich auf der PR noch hinzugefügt, wo ich mir nicht sicher bin ob eine Änderung im POM gewollt ist, oder ob die beim Rebase hinzugekommen ist.
