### ISSUE TITLE
Multitenancy auf prod deployen

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#832]
Einige Dinge müssen bei dem Deploy der Multitenancy durchgeführt werden.

- [ ] Flyway Schema Validierungen überschreiben (Hashes der Files, die angepasst werden mussten)
- [ ] Bisheriges Schema von Puzzle nach okr-pitc kopieren
- [ ] Initiale Team- und Rollenzuordnung nachführen (auch GUI oder in DB)

**Comment by MasterEvarior** [comment]
@peggimann Ist das noch aktuell oder hat sich das mit dem Deployment am Montag erledigt?

**Comment by MasterEvarior** [comment]
Das Ticket kann geschlossen werden, da das Multitenancy-Feature mit dem 3.0.0 Release auf Prod deployed wurde.
