### ISSUE TITLE
CHF Label

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#845]
Wenn die Einheit CHF ausgewählt wird, so zeigt die Ansicht `Alle Check-ins anzeigen` zweimal die Einheit.

### Anforderungen
- Die Einheit wird nicht Doppelt angezeigt

![Image](https://github.com/puzzle/okr/assets/113369749/c1bd4121-b988-413a-bbf5-97cef9610b3b)

### Akzeptanzkriterien
- [x] Der Bug ist behoben
- [x] E2E Tests sind ergänzt

**Comment by Miguel7373** [comment]
### Stand 31.10.2024

Ich habe den Bug entfernt und ein kleines clean up gemacht. Ich habe die zweite Pipe entfernt, je nachdem wie es aussehen muss, kann die auch gut wieder hinzugefügt werden, um das single responsibility Prinzip besser zu beachten.
Doch bleiben mir noch fragen bezüglich wie das ganze aussehen soll.
Muss alles als Suffix oder Präfix dargestellt werden oder ist es immer noch gemixt?
