### ISSUE TITLE
Fehlende Quarter erstellen bei Startup der Applikation

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#882]
Als Entwickler möchte ich, dass zu jedem Zeitpunkt die richtigen Quarter sowohl in den Testdaten wie auch in der Dev Datenbank vorhanden sind, so dass ich immer direkt mit entwickeln beginnen kann

**Anforderungen:**
* Aktuell ist es so, dass nur ein bestimmter Datensatz für Quarters in der Datenbank vorhanden ist. Dies führt zu Nullpointer Exceptions, wenn die Applikation gestartet wird und der aktuelle Quarter noch nicht vorhanden ist:
![Image](https://github.com/puzzle/okr/assets/17762787/6f875540-377c-41b7-ae16-251de74622db)
* Neben dem Batchjob, der die Quarters erstellt, müsste es eine andere Möglichkeit geben, fehlende Quarter zu erstellen. Eine Möglichkeit wäre, beim Startup der Applikation zu prüfen, ob alle nötigen Quarter da sind, und wenn nicht, diese zu erstellen.
* Egal wann ich die Applikation starte müsste sowohl das aktuelle Quarter sowie das nächste Quarter erstellt sein

**Comment by Makae** [comment]
Ich denke es wird schwierig werden dies unterschiedlichen Startzeiten von Geschäftsjahren zu machen.

Wie wäre es wenn wir bei dem Repository anstatt:
```java
   @Query(value = "Select q from Quarter q where q.startDate <= :date and q.endDate >= :date")
    Quarter getActiveQuarter(@Param("date") LocalDate date);
```
immer das letzte quarter zurückgeben, welches das kleinste End-Datum hat?
```java
   @Query(value = "Select q from Quarter q where q.startDate <= :date ORDER BY q.endDate ASC LIMIT 1")
    Quarter getActiveQuarter(@Param("date") LocalDate date);
```

Das würde zwar auch "alte" Quarters zurückgeben, wenn noch keines erstellt wurde.
