### ISSUE TITLE
Mandantenfähigkeit auf Demo Instanz deployen

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#921]
Als Produktmanager möchte ich, dass das OKR Tool mandantenfähig auf Staging getestet werden kann.

AKs:
* Das OKR Tool soll mandantenfähig auf der Demo Instanz deployed werden können (PITC und ACME)
* ACME soll auch auf der Demo Instanz mit einem eigenen Keycloak verbunden werden. Dieses kann z.B. in einem eigenen OpenShift Pod laufen

**Comment by janikEndtner** [comment]
Gemacht:
* Anpassen InitialData Skript, so dass dieses auf dem Multitenant auch läuft
* Konfiguration den Environment Variablen im GitLab Infrastructure Repo & Konfiguration der Secrets in OpenShift
* Anpassen der demo-deploy GitHub Pipeline, so dass das Docker Image für den Branch multitenancy_main deployed wird
* Initiales Datenbank Skript für die Erstellung der Tenant Schemas auf der Demo Datenbank ausgeführt

TODO:
* E2E Tests in deploy-demo Action wieder aktivieren
* Branch Protection für Multitenancy_main Branch hinzufügen
* Der Auskommentierte Step zum Setzen des neuen Images im YAML in der deploy-demo-action wieder einkommentieren und korrigieren. 
    * Abklären, wo die Variablen gespeichert sind
* Starkes Password die KeyCloak Demo Instanz setzen
* Anpassen der Klasse AbstractSchemaMultiTenantConnectionProvider, so dass Spring Boot Properties anstatt der spezifischen Hibernate Property Files für die Konfiguration der Datenbank Verbindung verwendet werden => müssen auf Demo überschrieben werden

**Comment by clean-coder** [comment]
**Stand: 08.08.2024**
OKR Ist seit dem 23.07.2024 bereit zum Testing auf `demo`
