### ISSUE TITLE
Hilfe Button geht nicht

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#927]
In der Applikation im Top Bar ist ein Hilfe Icon eingeblendet, welches die Puzzle- Hilfeseite zum OKR öffnen soll. 
Zur Zeit funktioniert dieser Button nicht. 

**To Reproduce**
1. Öffne OKR-Tool 
2. Klicke HilfeIcon

**Expected behavior**
Nach dem Klicken des HilfeIcons, sollte die Hinterlegte Hilfeseite in einem neuen Tab geöffnet werde.

### Akzeptanzkriterien
- [x] Hilfeseite öffnet sich in neuem Tab
- [x] E2E Test ist ergänzt für diese Situation.

**Comment by clean-coder** [comment]
Potentieller Fix auf: https://github.com/puzzle/okr/tree/bug/927_hilfe_button
