### ISSUE TITLE
Members einladen: Delete ermöglichen

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#931]
Als OKR Champion möchte ich Members, die ich eingeladen habe, wieder löschen und allenfalls updaten können, so dass ich meine Aktion rückgängig machen kann, wenn ich fälschlicherweise einen Member eingeladen habe.

AK:
* Im Sidebar Component gibt es einen Button "Member löschen" der nur für den OKR Champion sichtbar ist

![Image](https://github.com/user-attachments/assets/7f2c0792-975b-4746-b930-54feea20667a)

* Beim Klick auf diesen Button soll ein Dialog erscheinen "Soll dieser Member wirklich gelöscht werden?" 
* Falls bestätigt wird, wird der Member aus der Datenbank gelöscht. 
* Dies kann nur gemacht werden, falls der User kein Owner eines KeyResults ist
* Falls doch, wird eine entsprechende Fehlermeldung ausgegeben: "Der Member kann nicht gelöscht werden, weil er Owner eines KeyResults ist ([KEY_RESULT_TITLE], [OBJECTIVE_TITLE])

**Comment by clean-coder** [comment]
Es gibt einen Branch `https://github.com/puzzle/okr/tree/feature/931_delete_member`.  Dort wird das UI (Angular) erweitert für das Löschen von Members.

**Comment by clean-coder** [comment]
Status: `https://github.com/puzzle/okr/tree/feature/931_delete_member`

**Frontend**
- delete-user.component (löschen Member + backendCall + validation Rules)
- alert-dialog.component (MatDialog nur mit einem Button "Schliessen")
- Anzeige "Member löschen", nur wenn OkrUser die Rolle OkrChampion hat
- Client jest Tests
- Client Cypress Tests 


**Backend**
- 2 neue Rest Endpoints
  - Support für Frontend Validations: "check if user is owner of KeyResult"
  - Löschen eines Users
- TODOs:
  - Löschen eines Users:  Authorization Checking implementieren
  - Rückgabe, in welchen KeyResults der user owner ist
  - jUnit Tests

**Comment by clean-coder** [comment]
Habe den aktuellen Stand der Entwicklung dieses Features auf einen neuen Branch (gezogen von `dev`) geschoben:
`https://github.com/puzzle/okr/tree/refs/heads/feature/931_delete_member_dev_branch`
