### ISSUE TITLE
Demo Instanz Restanzen

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#984]
Folgende Dinge müssen für die Demo Instanz noch verbessert werden:
- [x] Die E2E Tests in deploy-demo Action wurden deaktiviert. Es muss abeklärt werden, ob es die beim Deploy von Demo wirklich braucht und entweder wieder aktiviert werden oder ganz entfernt
   -  Die e2e werden beim deployment ausgeführt
 
* Die Datenbank wird nun mittels Dump und nicht mehr via Init Database Skript zurückgesetzt. Es soll abgeklärt werden, ob dies so bleiben soll.
    * Falls ja, sollte das zurücksetzen der Demo Umgebung wenn möglich in einem eigenen GitLab Job gemacht werden und das Init Database Skript müsste gelöscht werden.
    * Falls nein muss eine Lösung gefunden werden, wie das Init Database Skript für mehrere Mandanten funktioniert
* In der Deploy Demo Action wurde des Step zum Setzen des Images im YAML der deploy-demo-action deaktiviert. Es soll entschieden werden, ob die Version automatisch deployed werden soll. Wenn ja müsste der Step wieder einkommentiert werden
*    ~~Es muss beachtet werden, dass aktuell ein eigener Branch "Multitenancy_main" deployed wird. Dieser müsste nach dem Merge in Master wieder zurückgestellt werden.~~

**Comment by clean-coder** [comment]
Die ursprüngliche Idee war, dass man die Demo Umgebung via Init Skript zurücksetzt. Die Daten dafür sind im `afterMigrate__0_initialData.sql` im `data-migration-demo` Folder.

Mit diesem Ansatz gibt es die Möglichkeit, dass man die DB mit jedem Neustart des `backend` Prozesses bzw. Pods zurückgesetzt wird. Dafür muss man im `application-dev.properties`  den Key `spring.flyway.locations` ergänzen um `data-migration-demo`. Dies würde dann folgendermassen aussehen:

`spring.flyway.locations=classpath:db/migration,classpath:db/data-migration-demo,classpath:db/callback`

**Comment by clean-coder** [comment]
Im Planung Meeting wurde gewünscht, dass man zusätzlich eine GitHub Action implementiert, die man manuell triggern kann, die dann das Backend auf der Demo Umgebung herunterfährt. Durch das automatische Wieder-Hochfahren des Backends (via OpenShift), wird die DB wieder auf den initialen Stand gesetzt.
