### ISSUE TITLE
Verschiedene Datenbankuser für verschiedene Mandanten

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#985]
Als DevOps möchte ich, dass verschiedene Datenbankuser pro Mandant verwendet werden, damit die Sicherheit gegenüber mandantenübergreifenden Datenbankabfragen erhöht wird.

**Hintergrund**:
Die Applikation wurde so programmiert, dass pro Mandant ein Datenbankuser hinterlegt werden kann. Ausserdem gibt es einen Hibernate Datenbankuser, der die Schemaänderungen vornimmt. Auf der Demo Instanz wurde überall derselbe Datenbankuser konfiguriert, weil Ansible von Sys noch nicht so weit war, verschiedene Datenbankuser zu hinterlegen. Spätestens für die Produktion müsste dies aus Sicherheitsgründen aber möglich sein.

**AK**:
* Es wurde mit Sys abgeklärt, ab wann verschiedene Datenbankuser konfiguriert werden können
* Die unterschiedlichen User wurden konfiguriert oder es wurde ein Folgetask für die Konfiguration erstellt (falls durch Sys noch nicht möglich)

**Comment by clean-coder** [comment]
Duplikat von https://github.com/puzzle/okr/issues/1077
